export interface QuestionDefinition {
  id: string;
  domain: string;
  level: number;
  order: number;
  difficulty: "warm-up" | "core" | "challenging" | "boss";
  title: string;
  stakeholder: {
    name: string;
    role: string;
  };
  request: string;
  context_notes: string;
  concepts: string[];
  expected_columns: string[];
  reference_sql: string;
  validation: {
    order_sensitive: boolean;
    column_names_sensitive: boolean;
    numeric_tolerance: number;
  };
  hints: string[];
  solution_explanation: string;
  xp: number;
  estimated_minutes: number;
}

export const ECOM_L1_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ecom-L1-001",
    domain: "ecommerce",
    level: 1,
    order: 1,
    difficulty: "warm-up",
    title: "All Products in Electronics",
    stakeholder: { name: "Alex Rivera", role: "CEO" },
    request: "We are reviewing our tech catalog for the upcoming quarterly review. Can you pull a list of all products in the 'Electronics' category with their price and stock quantity?",
    context_notes: "Join products with categories to filter for 'Electronics'. Show product name, price, and stock_quantity.",
    concepts: ["SELECT", "WHERE", "INNER JOIN"],
    expected_columns: ["name", "price", "stock_quantity"],
    reference_sql: `
      SELECT p.name, p.price, p.stock_quantity
      FROM products p
      JOIN categories c ON p.category_id = c.id
      WHERE c.name = 'Electronics'
      ORDER BY p.name;
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.01,
    },
    hints: [
      "Join the 'products' table with 'categories' on category_id = categories.id.",
      "Filter using WHERE categories.name = 'Electronics'.",
      "Select only the 3 columns: name, price, stock_quantity.",
    ],
    solution_explanation: "This query performs an INNER JOIN between products and categories to filter items specifically mapped to the Electronics category.",
    xp: 10,
    estimated_minutes: 4,
  },
  {
    id: "ecom-L1-002",
    domain: "ecommerce",
    level: 1,
    order: 2,
    difficulty: "warm-up",
    title: "Top 5 Highest Value Orders",
    stakeholder: { name: "Rachel Green", role: "VP of Sales" },
    request: "We want to send personalized thank-you gifts to the biggest orders placed in 2025. What are the top 5 highest order totals in the system?",
    context_notes: "Return the order id, customer_id, and total_amount, sorted by total_amount descending. Limit to 5.",
    concepts: ["SELECT", "ORDER BY", "LIMIT"],
    expected_columns: ["id", "customer_id", "total_amount"],
    reference_sql: `
      SELECT id, customer_id, total_amount
      FROM orders
      ORDER BY total_amount DESC
      LIMIT 5;
    `,
    validation: {
      order_sensitive: true,
      column_names_sensitive: false,
      numeric_tolerance: 0.01,
    },
    hints: [
      "Query the 'orders' table directly.",
      "Sort by 'total_amount DESC' to place the highest amounts first.",
      "Use 'LIMIT 5' to retrieve only the top 5 records.",
    ],
    solution_explanation: "Using ORDER BY total_amount DESC alongside LIMIT 5 isolates the highest-value transactions.",
    xp: 10,
    estimated_minutes: 3,
  },
  {
    id: "ecom-L1-003",
    domain: "ecommerce",
    level: 1,
    order: 3,
    difficulty: "warm-up",
    title: "Customers Located in the Western Region",
    stakeholder: { name: "Marcus Bell", role: "Head of Support" },
    request: "We are opening a regional support center on the West Coast. How many customers are registered in the 'West' region, and what are their names and emails?",
    context_notes: "Return first_name, last_name, and email for all customers where region = 'West'.",
    concepts: ["SELECT", "WHERE", "ORDER BY"],
    expected_columns: ["first_name", "last_name", "email"],
    reference_sql: `
      SELECT first_name, last_name, email
      FROM customers
      WHERE region = 'West'
      ORDER BY last_name, first_name;
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.01,
    },
    hints: [
      "Query the 'customers' table.",
      "Filter with WHERE region = 'West'.",
      "Include first_name, last_name, and email.",
    ],
    solution_explanation: "A straightforward filter on the region column extracts the West coast customer demographic.",
    xp: 10,
    estimated_minutes: 3,
  },
  {
    id: "ecom-L1-004",
    domain: "ecommerce",
    level: 1,
    order: 4,
    difficulty: "core",
    title: "Total Revenue Generated by Product Category",
    stakeholder: { name: "Priya Nair", role: "Finance Lead" },
    request: "I need to report quarterly department revenue. What is the total revenue generated by each category, based on order items sold?",
    context_notes: "Multiply order_items.quantity by order_items.unit_price, sum it per category name, and alias as total_revenue.",
    concepts: ["INNER JOIN", "GROUP BY", "SUM", "AGGREGATE"],
    expected_columns: ["category_name", "total_revenue"],
    reference_sql: `
      SELECT c.name AS category_name, SUM(oi.quantity * oi.unit_price) AS total_revenue
      FROM categories c
      JOIN products p ON c.id = p.category_id
      JOIN order_items oi ON p.id = oi.product_id
      GROUP BY c.name
      ORDER BY total_revenue DESC;
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.05,
    },
    hints: [
      "You will need to join 'categories', 'products', and 'order_items'.",
      "Calculate revenue using SUM(quantity * unit_price).",
      "Group by the category name.",
    ],
    solution_explanation: "Joining through products to order_items allows aggregating total sales volume grouped by category.",
    xp: 20,
    estimated_minutes: 7,
  },
  {
    id: "ecom-L1-005",
    domain: "ecommerce",
    level: 1,
    order: 5,
    difficulty: "core",
    title: "Delivered Orders Placed in Q4 2025",
    stakeholder: { name: "Liam Vance", role: "Ops Manager" },
    request: "For our end-of-year logistics audit, how many orders were successfully delivered during Q4 2025 (October 1 to December 31, 2025)?",
    context_notes: "Return a single count named delivered_count for orders where status = 'delivered' and order_date is between '2025-10-01' and '2025-12-31 23:59:59'.",
    concepts: ["COUNT", "WHERE", "BETWEEN", "DATE FILTER"],
    expected_columns: ["delivered_count"],
    reference_sql: `
      SELECT COUNT(*) AS delivered_count
      FROM orders
      WHERE status = 'delivered'
        AND order_date >= '2025-10-01'
        AND order_date <= '2025-12-31 23:59:59';
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.0,
    },
    hints: [
      "Use COUNT(*) from orders.",
      "Check both status = 'delivered' and the date range.",
      "Remember that Q4 starts on Oct 1 and ends on Dec 31.",
    ],
    solution_explanation: "Filters orders by delivery status and checks temporal boundaries for the fourth calendar quarter.",
    xp: 20,
    estimated_minutes: 5,
  },
  {
    id: "ecom-L1-006",
    domain: "ecommerce",
    level: 1,
    order: 6,
    difficulty: "core",
    title: "Average Order Value by Status",
    stakeholder: { name: "Sarah Jenkins", role: "VP of Growth" },
    request: "We want to see how average basket sizes differ between delivered orders and cancelled/returned ones. Can you show average total_amount per status?",
    context_notes: "Group orders by status, calculate AVG(total_amount) rounded to 2 decimals, and sort by average_order_value DESC.",
    concepts: ["GROUP BY", "AVG", "ROUND", "ORDER BY"],
    expected_columns: ["status", "average_order_value"],
    reference_sql: `
      SELECT status, ROUND(AVG(total_amount), 2) AS average_order_value
      FROM orders
      GROUP BY status
      ORDER BY average_order_value DESC;
    `,
    validation: {
      order_sensitive: true,
      column_names_sensitive: false,
      numeric_tolerance: 0.05,
    },
    hints: [
      "Select status and ROUND(AVG(total_amount), 2).",
      "Group by status.",
      "Order by the calculated average in descending order.",
    ],
    solution_explanation: "Aggregating with AVG(total_amount) across status groups reveals transactional health patterns.",
    xp: 20,
    estimated_minutes: 5,
  },
  {
    id: "ecom-L1-007",
    domain: "ecommerce",
    level: 1,
    order: 7,
    difficulty: "core",
    title: "Customers Who Have Never Placed an Order",
    stakeholder: { name: "Daniel Craig", role: "Growth Analyst" },
    request: "Our marketing team is building a win-back drip for registered accounts that never bought anything. Which customers have zero orders in the database?",
    context_notes: "Return id, first_name, last_name, email from customers where there is no matching record in orders.",
    concepts: ["LEFT JOIN", "NULL HANDLING", "IS NULL"],
    expected_columns: ["id", "first_name", "last_name", "email"],
    reference_sql: `
      SELECT c.id, c.first_name, c.last_name, c.email
      FROM customers c
      LEFT JOIN orders o ON c.id = o.customer_id
      WHERE o.id IS NULL
      ORDER BY c.id;
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.0,
    },
    hints: [
      "Use a LEFT JOIN from customers to orders.",
      "Filter for rows where the joined table's primary key IS NULL (e.g. o.id IS NULL).",
      "Select customer identification fields.",
    ],
    solution_explanation: "A classic anti-join using LEFT JOIN ... WHERE orders.id IS NULL extracts non-purchasing accounts.",
    xp: 20,
    estimated_minutes: 6,
  },
  {
    id: "ecom-L1-008",
    domain: "ecommerce",
    level: 1,
    order: 8,
    difficulty: "challenging",
    title: "High-Volume Customers (>3 Orders)",
    stakeholder: { name: "Chloe Bennett", role: "VP Customer Success" },
    request: "We are introducing a VIP tier. Find all customers who have placed strictly more than 3 orders. Show customer id, first name, last name, and their total order count.",
    context_notes: "Join customers with orders, group by customer id and names, and filter with HAVING COUNT(o.id) > 3.",
    concepts: ["INNER JOIN", "GROUP BY", "HAVING", "COUNT"],
    expected_columns: ["id", "first_name", "last_name", "order_count"],
    reference_sql: `
      SELECT c.id, c.first_name, c.last_name, COUNT(o.id) AS order_count
      FROM customers c
      JOIN orders o ON c.id = o.customer_id
      GROUP BY c.id, c.first_name, c.last_name
      HAVING COUNT(o.id) > 3
      ORDER BY order_count DESC, c.id ASC;
    `,
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0.0,
    },
    hints: [
      "Join customers and orders.",
      "Group by c.id, c.first_name, c.last_name.",
      "Filter the aggregated group with HAVING COUNT(o.id) > 3.",
    ],
    solution_explanation: "The HAVING clause applies filtering criteria on aggregated data after GROUP BY execution.",
    xp: 35,
    estimated_minutes: 8,
  },
  {
    id: "ecom-L1-009",
    domain: "ecommerce",
    level: 1,
    order: 9,
    difficulty: "challenging",
    title: "Low Inventory Restock Alert",
    stakeholder: { name: "Tony Stark", role: "Warehouse Lead" },
    request: "We have stockouts looming in our fulfillment center! Which active products currently have fewer than 25 units in stock? Show product name, category name, price, and current stock, ordered from lowest stock to highest.",
    context_notes: "Join products and categories. Filter where stock_quantity < 25. Order by stock_quantity ASC.",
    concepts: ["INNER JOIN", "WHERE", "ORDER BY ASC"],
    expected_columns: ["product_name", "category_name", "price", "stock_quantity"],
    reference_sql: `
      SELECT p.name AS product_name, c.name AS category_name, p.price, p.stock_quantity
      FROM products p
      JOIN categories c ON p.category_id = c.id
      WHERE p.stock_quantity < 25
      ORDER BY p.stock_quantity ASC, p.name ASC;
    `,
    validation: {
      order_sensitive: true,
      column_names_sensitive: false,
      numeric_tolerance: 0.01,
    },
    hints: [
      "Join products with categories.",
      "Filter where p.stock_quantity < 25.",
      "Sort with ORDER BY stock_quantity ASC.",
    ],
    solution_explanation: "This query pinpoints depleted inventory lines sorted in ascending order for replenishment.",
    xp: 35,
    estimated_minutes: 6,
  },
  {
    id: "ecom-L1-010",
    domain: "ecommerce",
    level: 1,
    order: 10,
    difficulty: "boss",
    title: "Boss: Executive Regional Performance Summary",
    stakeholder: { name: "Alex Rivera", role: "CEO" },
    request: "I am presenting to the board tomorrow. I need an executive breakdown of delivered sales performance by customer region. For each region, calculate the total delivered revenue, the count of delivered orders, and the average revenue per delivered order. Sort by total revenue descending.",
    context_notes: "Filter for status = 'delivered'. Aggregate by customers.region. Round average revenue to 2 decimals.",
    concepts: ["INNER JOIN", "WHERE", "GROUP BY", "SUM", "COUNT", "AVG", "ROUND", "ORDER BY"],
    expected_columns: ["region", "total_revenue", "order_count", "avg_order_value"],
    reference_sql: `
      SELECT 
        c.region,
        SUM(o.total_amount) AS total_revenue,
        COUNT(o.id) AS order_count,
        ROUND(AVG(o.total_amount), 2) AS avg_order_value
      FROM customers c
      JOIN orders o ON c.id = o.customer_id
      WHERE o.status = 'delivered'
      GROUP BY c.region
      ORDER BY total_revenue DESC;
    `,
    validation: {
      order_sensitive: true,
      column_names_sensitive: false,
      numeric_tolerance: 0.05,
    },
    hints: [
      "Join customers c and orders o on c.id = o.customer_id.",
      "Filter with WHERE o.status = 'delivered'.",
      "Group by c.region.",
      "Select region, SUM(total_amount), COUNT(o.id), and ROUND(AVG(total_amount), 2).",
      "Order by total_revenue DESC.",
    ],
    solution_explanation: "The Level 1 Boss query combines multi-table joins, status filtering, multi-metric aggregations, rounding, and descending ranking into an executive reporting query.",
    xp: 60,
    estimated_minutes: 12,
  },
];
