const fs = require('fs');
const path = require('path');

const q = (id, domain, level, order, difficulty, title, name, role, request, notes, concepts, cols, sql, order_sensitive, hints, explanation, xp, mins) => ({
  id, domain, level, order, difficulty, title,
  stakeholder: { name, role },
  request, context_notes: notes, concepts,
  expected_columns: cols,
  reference_sql: sql,
  validation: { order_sensitive: order_sensitive === 't', column_names_sensitive: false, numeric_tolerance: 0 },
  hints: Array.isArray(hints) ? hints : [hints],
  solution_explanation: explanation,
  xp, estimated_minutes: mins
});

const L1 = [
  // WARM-UP 1–25: Single-table SELECT, WHERE filters, ORDER BY, LIMIT
  q('fin-L1-001','finance',1,1,'warm-up','Active Banking Branches Directory','Rachel Adams','Director of Branch Operations',
    'Morning! I need a clean directory of our banking branches with their physical location. Please pull the branch name, city, and state, sorted alphabetically by branch name.',
    'Query the branches table for branch_name, city, and state.',['SELECT','ORDER BY'],['branch_name','city','state'],
    "SELECT branch_name, city, state FROM branches ORDER BY branch_name ASC;",'t',
    ['Select branch_name, city, state from branches.','Order alphabetically by branch_name.'],'Retrieves active bank branches across regional banking divisions.',15,3),

  q('fin-L1-002','finance',1,2,'warm-up','High Credit Score Commercial Customers','Victor Vance','Head of Risk & Compliance',
    'Victor here from Risk. Can you bring up our prime credit clients? I need customer name, credit score, and annual income for everyone with a credit score of 780 or higher, ordered highest score first.',
    'Filter customers WHERE credit_score >= 780.',['SELECT','WHERE','ORDER BY'],['name','credit_score','annual_income'],
    "SELECT name, credit_score, annual_income FROM customers WHERE credit_score >= 780 ORDER BY credit_score DESC;",'t',
    ['Filter WHERE credit_score >= 780.','Order descending by credit_score.'],'Identifies prime credit score accounts for preferred institutional services.',15,4),

  q('fin-L1-003','finance',1,3,'warm-up','High Net Worth Depository Accounts','Arthur Pendleton','Chief Wealth Advisor',
    'Arthur from Wealth Management. Could you pull all active accounts holding a balance of $100,000 or greater? Show account id, customer id, and balance, highest balance first.',
    'Query accounts table WHERE balance >= 100000.00 and status = active.',['SELECT','WHERE','AND','ORDER BY'],['id','customer_id','balance'],
    "SELECT id, customer_id, balance FROM accounts WHERE balance >= 100000.00 AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter accounts where balance >= 100000.00 AND status = active.','Order by balance DESC.'],'Surfaces private wealth tier account relationships.',15,4),

  q('fin-L1-004','finance',1,4,'warm-up','Merchants Classified as High Risk','Victor Vance','Head of Risk & Compliance',
    'We are running our weekly AML and anti-fraud merchant audit. Bring me the name, category, and city of all merchants flagged with risk_level High_Risk.',
    'Filter merchants WHERE risk_level = High_Risk.',['SELECT','WHERE'],['name','category','city'],
    "SELECT name, category, city FROM merchants WHERE risk_level = 'High_Risk' ORDER BY name ASC;",'f',
    ['Query merchants table where risk_level = High_Risk.','Select name, category, city.'],'Surfaces high-risk commercial payment terminals subject to enhanced scrutiny.',15,4),

  q('fin-L1-005','finance',1,5,'warm-up','Recent High-Value Wire Transactions','Victor Vance','Head of Risk & Compliance',
    'Compliance review: I need to review large wire transfers. Pull transaction id, account id, amount, and description for all wire transactions of $5,000 or more, latest first. Limit to top 20.',
    'Filter transactions WHERE transaction_type = wire AND amount >= 5000.00.',['SELECT','WHERE','AND','ORDER BY','LIMIT'],['id','account_id','amount','description'],
    "SELECT id, account_id, amount, description FROM transactions WHERE transaction_type = 'wire' AND amount >= 5000.00 ORDER BY created_at DESC LIMIT 20;",'t',
    ['Filter WHERE transaction_type = wire AND amount >= 5000.00.','Order by created_at DESC LIMIT 20.'],'Isolates high-dollar electronic wire transfers for AML currency monitoring.',15,4),

  q('fin-L1-006','finance',1,6,'warm-up','Active Credit Cards with Premium Limits','Elena Rostova','VP of Retail Lending',
    'Card portfolio audit: Show me all active cards that have a daily limit of $8,000 or higher. Return card id, card type, masked card number, and daily limit.',
    'Filter cards WHERE daily_limit >= 8000.00 and status = active.',['SELECT','WHERE','AND'],['id','card_type','card_number_masked','daily_limit'],
    "SELECT id, card_type, card_number_masked, daily_limit FROM cards WHERE daily_limit >= 8000.00 AND status = 'active' ORDER BY daily_limit DESC;",'t',
    ['Filter cards where daily_limit >= 8000.00 and status = active.','Order by daily_limit DESC.'],'Monitors premier credit and debit card cardholder facilities.',15,4),

  q('fin-L1-007','finance',1,7,'warm-up','Branches With Over $20M Vault Cash Limit','Rachel Adams','Director of Branch Operations',
    'Treasury review: Which of our regional branches are authorized to hold more than $20,000,000 in physical vault cash? Return branch name, city, and vault cash limit.',
    'Filter branches WHERE vault_cash_limit > 20000000.00.',['SELECT','WHERE'],['branch_name','city','vault_cash_limit'],
    "SELECT branch_name, city, vault_cash_limit FROM branches WHERE vault_cash_limit > 20000000.00 ORDER BY vault_cash_limit DESC;",'t',
    ['Filter WHERE vault_cash_limit > 20000000.00.','Order descending by vault_cash_limit.'],'Identifies primary regional depository vaults managing large cash reserves.',15,4),

  q('fin-L1-008','finance',1,8,'warm-up','Frozen or Monitored Accounts','Victor Vance','Head of Risk & Compliance',
    'Risk alert: Pull all accounts currently flagged with status frozen. Show account id, customer id, account type, and balance.',
    'Filter accounts WHERE status = frozen.',['SELECT','WHERE'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE status = 'frozen' ORDER BY balance DESC;",'t',
    ['Filter accounts where status = frozen.','Order by balance DESC.'],'Audits frozen depository assets under compliance hold.',15,4),

  q('fin-L1-009','finance',1,9,'warm-up','Customers in New York or Boston','Arthur Pendleton','Chief Wealth Advisor',
    'Northeast regional outreach: Show me customer name, branch city, and annual income for account holders located in New York or Boston, ordered by city.',
    'Filter customers WHERE branch_city IN (New York, Boston).',['SELECT','WHERE','IN','ORDER BY'],['name','branch_city','annual_income'],
    "SELECT name, branch_city, annual_income FROM customers WHERE branch_city IN ('New York', 'Boston') ORDER BY branch_city ASC, name ASC;",'f',
    ['Filter WHERE branch_city IN (\'New York\', \'Boston\').','Order by branch_city and name.'],'Targets Northeast wealth advisory client prospect lists.',15,4),

  q('fin-L1-010','finance',1,10,'warm-up','Transactions Involving Regulatory or Settlement Fees','Victor Vance','Head of Risk & Compliance',
    'Fee audit: Pull all ledger transactions categorized as fee. Display transaction id, account id, amount, and description.',
    'Filter transactions WHERE transaction_type = fee.',['SELECT','WHERE'],['id','account_id','amount','description'],
    "SELECT id, account_id, amount, description FROM transactions WHERE transaction_type = 'fee' ORDER BY amount DESC;",'t',
    ['Filter transactions where transaction_type = fee.','Order by amount DESC.'],'Reviews assessed maintenance, overdraft, and transaction fees.',15,4),

  q('fin-L1-011','finance',1,11,'warm-up','Speculative Risk Rated Customers','Victor Vance','Head of Risk & Compliance',
    'Credit risk mitigation: Pull customer name, credit score, and annual income for customers marked with risk_rating Speculative.',
    'Filter customers WHERE risk_rating = Speculative.',['SELECT','WHERE'],['name','credit_score','annual_income'],
    "SELECT name, credit_score, annual_income FROM customers WHERE risk_rating = 'Speculative' ORDER BY credit_score ASC;",'f',
    ['Filter WHERE risk_rating = Speculative.','Order by credit_score ASC.'],'Surfaces accounts subject to strict borrowing and credit exposure caps.',15,4),

  q('fin-L1-012','finance',1,12,'warm-up','Active Money Market Accounts','Arthur Pendleton','Chief Wealth Advisor',
    'Money market yield check: List all active accounts under account_type money_market. Show account id, customer id, and balance, sorted highest balance first.',
    'Filter accounts WHERE account_type = money_market and status = active.',['SELECT','WHERE','AND','ORDER BY'],['id','customer_id','balance'],
    "SELECT id, customer_id, balance FROM accounts WHERE account_type = 'money_market' AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter accounts where account_type = money_market and status = active.','Order by balance DESC.'],'Reviews liquid yield-bearing money market deposits.',15,4),

  q('fin-L1-013','finance',1,13,'warm-up','Platinum Amex Cards Portfolio','Elena Rostova','VP of Retail Lending',
    'Card issuer report: Show all cards of card_type Platinum_Amex. Return card id, masked card number, daily limit, and status.',
    'Filter cards WHERE card_type = Platinum_Amex.',['SELECT','WHERE'],['id','card_number_masked','daily_limit','status'],
    "SELECT id, card_number_masked, daily_limit, status FROM cards WHERE card_type = 'Platinum_Amex' ORDER BY daily_limit DESC;",'t',
    ['Filter WHERE card_type = Platinum_Amex.','Order by daily_limit DESC.'],'Audits the bank co-branded ultra-high-limit charge card tier.',15,4),

  q('fin-L1-014','finance',1,14,'warm-up','Merchants in San Francisco and Miami','Rachel Adams','Director of Branch Operations',
    'Merchant acquiring coverage: List all merchant names, categories, and cities for merchants operating in San Francisco or Miami.',
    'Filter merchants WHERE city IN (San Francisco, Miami).',['SELECT','WHERE','IN'],['name','category','city'],
    "SELECT name, category, city FROM merchants WHERE city IN ('San Francisco', 'Miami') ORDER BY city ASC, name ASC;",'f',
    ['Filter WHERE city IN (\'San Francisco\', \'Miami\').','Order by city, name.'],'Assesses commercial merchant penetration in key metropolitan markets.',15,4),

  q('fin-L1-015','finance',1,15,'warm-up','Cash Deposit Transactions Over $3,000','Victor Vance','Head of Risk & Compliance',
    'Bank Secrecy Act monitoring: Retrieve transaction id, account id, amount, and timestamp for all transactions categorized as deposit with amount >= $3,000, newest first. Limit to top 25.',
    'Filter transactions WHERE transaction_type = deposit AND amount >= 3000.00.',['SELECT','WHERE','AND','ORDER BY','LIMIT'],['id','account_id','amount','created_at'],
    "SELECT id, account_id, amount, created_at FROM transactions WHERE transaction_type = 'deposit' AND amount >= 3000.00 ORDER BY created_at DESC LIMIT 25;",'t',
    ['Filter WHERE transaction_type = deposit AND amount >= 3000.00.','Order by created_at DESC LIMIT 25.'],'Screens cash inflows nearing institutional anti-structuring thresholds.',15,4),

  q('fin-L1-016','finance',1,16,'warm-up','Branches Managed in California and Texas','Rachel Adams','Director of Branch Operations',
    'Western and Southern expansion: List branch name, state, and manager name for all branches located in California (CA) or Texas (TX).',
    'Filter branches WHERE state IN (CA, TX).',['SELECT','WHERE','IN'],['branch_name','state','manager_name'],
    "SELECT branch_name, state, manager_name FROM branches WHERE state IN ('CA', 'TX') ORDER BY state ASC, branch_name ASC;",'f',
    ['Filter WHERE state IN (\'CA\', \'TX\').','Order by state, branch_name.'],'Directories regional branch management across CA and TX banking networks.',15,4),

  q('fin-L1-017','finance',1,17,'warm-up','Customers With Annual Income Exceeding $300,000','Arthur Pendleton','Chief Wealth Advisor',
    'Affluent customer prospecting: Pull customer name, branch city, and annual income for customers whose annual income is strictly greater than $300,000.',
    'Filter customers WHERE annual_income > 300000.00.',['SELECT','WHERE','ORDER BY'],['name','branch_city','annual_income'],
    "SELECT name, branch_city, annual_income FROM customers WHERE annual_income > 300000.00 ORDER BY annual_income DESC;",'t',
    ['Filter WHERE annual_income > 300000.00.','Order by annual_income DESC.'],'Segments top-tier wage earners for private banking onboarding.',15,4),

  q('fin-L1-018','finance',1,18,'warm-up','Investment Account Balances','Arthur Pendleton','Chief Wealth Advisor',
    'Brokerage balances review: Show account id, customer id, and balance for all accounts under account_type investment.',
    'Filter accounts WHERE account_type = investment.',['SELECT','WHERE','ORDER BY'],['id','customer_id','balance'],
    "SELECT id, customer_id, balance FROM accounts WHERE account_type = 'investment' ORDER BY balance DESC;",'t',
    ['Filter WHERE account_type = investment.','Order by balance DESC.'],'Audits customer self-directed and managed brokerage cash balances.',15,4),

  q('fin-L1-019','finance',1,19,'warm-up','Low Risk Customers With Moderate Income','Victor Vance','Head of Risk & Compliance',
    'Safe retail lending: Find all customers with risk_rating Low and credit_score strictly greater than 700. Return customer name, credit score, and risk rating.',
    'Filter customers WHERE risk_rating = Low AND credit_score > 700.',['SELECT','WHERE','AND'],['name','credit_score','risk_rating'],
    "SELECT name, credit_score, risk_rating FROM customers WHERE risk_rating = 'Low' AND credit_score > 700 ORDER BY credit_score DESC;",'t',
    ['Filter WHERE risk_rating = Low AND credit_score > 700.','Order by credit_score DESC.'],'Identifies low-default credit candidates for auto and mortgage originations.',15,4),

  q('fin-L1-020','finance',1,20,'warm-up','International or Non-Domestic Merchants','Victor Vance','Head of Risk & Compliance',
    'Cross-border transaction risk: List merchant name, category, and country for any merchant where country is NOT USA.',
    'Filter merchants WHERE country != USA.',['SELECT','WHERE'],['name','category','country'],
    "SELECT name, category, country FROM merchants WHERE country != 'USA' ORDER BY name ASC;",'f',
    ['Filter WHERE country != USA.','Select name, category, country.'],'Surfaces non-domestic merchant payment entities for foreign exchange fee audits.',15,4),

  q('fin-L1-021','finance',1,21,'warm-up','Debit Cards Issued on Active Accounts','Elena Rostova','VP of Retail Lending',
    'Everyday banking card volume: Show card id, masked card number, daily limit, and status for cards with card_type Visa_Debit.',
    'Filter cards WHERE card_type = Visa_Debit.',['SELECT','WHERE'],['id','card_number_masked','daily_limit','status'],
    "SELECT id, card_number_masked, daily_limit, status FROM cards WHERE card_type = 'Visa_Debit' ORDER BY daily_limit DESC;",'t',
    ['Filter WHERE card_type = Visa_Debit.','Order by daily_limit DESC.'],'Reviews standard debit card issuing limits and card status.',15,4),

  q('fin-L1-022','finance',1,22,'warm-up','Large Withdrawal Transactions ($4,000+)','Victor Vance','Head of Risk & Compliance',
    'Liquidity outflow surveillance: Pull transaction id, account id, amount, and timestamp for all transactions of transaction_type withdrawal where amount >= $4,000. Limit to top 20.',
    'Filter transactions WHERE transaction_type = withdrawal AND amount >= 4000.00.',['SELECT','WHERE','AND','ORDER BY','LIMIT'],['id','account_id','amount','created_at'],
    "SELECT id, account_id, amount, created_at FROM transactions WHERE transaction_type = 'withdrawal' AND amount >= 4000.00 ORDER BY created_at DESC LIMIT 20;",'t',
    ['Filter WHERE transaction_type = withdrawal AND amount >= 4000.00.','Order by created_at DESC LIMIT 20.'],'Tracks significant depository cash and wire withdrawals.',15,4),

  q('fin-L1-023','finance',1,23,'warm-up','Closed Depository Accounts','Arthur Pendleton','Chief Wealth Advisor',
    'Account attrition audit: Show account id, customer id, account type, and balance for accounts flagged with status closed.',
    'Filter accounts WHERE status = closed.',['SELECT','WHERE'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE status = 'closed' ORDER BY id ASC;",'f',
    ['Filter accounts where status = closed.','Select id, customer_id, account_type, balance.'],'Surfaces closed customer account ledgers for customer churn analysis.',15,4),

  q('fin-L1-024','finance',1,24,'warm-up','Branch Vault Capacity Below $15M','Rachel Adams','Director of Branch Operations',
    'Regional branch liquidity: Find all branches where vault_cash_limit is strictly less than $15,000,000. Return branch name, city, state, and vault cash limit.',
    'Filter branches WHERE vault_cash_limit < 15000000.00.',['SELECT','WHERE'],['branch_name','city','state','vault_cash_limit'],
    "SELECT branch_name, city, state, vault_cash_limit FROM branches WHERE vault_cash_limit < 15000000.00 ORDER BY vault_cash_limit ASC;",'t',
    ['Filter WHERE vault_cash_limit < 15000000.00.','Order by vault_cash_limit ASC.'],'Identifies smaller satellite branch offices with lean vault storage thresholds.',15,4),

  q('fin-L1-025','finance',1,25,'warm-up','Customers With Credit Score Below 650','Elena Rostova','VP of Retail Lending',
    'Subprime portfolio monitoring: Find customers whose credit score is strictly less than 650. Show customer name, credit score, annual income, and risk rating.',
    'Filter customers WHERE credit_score < 650.',['SELECT','WHERE','ORDER BY'],['name','credit_score','annual_income','risk_rating'],
    "SELECT name, credit_score, annual_income, risk_rating FROM customers WHERE credit_score < 650 ORDER BY credit_score ASC;",'t',
    ['Filter WHERE credit_score < 650.','Order by credit_score ASC.'],'Flags credit-impaired retail customers for risk pricing and loan reserve allocations.',15,4),

  // CORE 26–50: Aggregations, GROUP BY, Financial Statistics & Account Totals
  q('fin-L1-026','finance',1,26,'core','Total Depository Balances by Account Type','Arthur Pendleton','Chief Wealth Advisor',
    'Balance sheet breakdown: For each account type (checking, savings, money_market, investment, credit), calculate total balance and total active accounts. Order highest balance first.',
    'GROUP BY account_type on accounts WHERE status = active.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['account_type','total_balance','active_accounts'],
    "SELECT account_type, ROUND(SUM(balance), 2) AS total_balance, COUNT(id) AS active_accounts FROM accounts WHERE status = 'active' GROUP BY account_type ORDER BY total_balance DESC;",'t',
    ['Group accounts by account_type filtering for status = active.','Calculate SUM(balance) and COUNT(id).' ],'Executive asset breakdown summarizing active deposits by account class.',20,5),

  q('fin-L1-027','finance',1,27,'core','Customer Count by Risk Rating Category','Victor Vance','Head of Risk & Compliance',
    'Risk distribution: How many customers fall into each risk rating tier (Low, Moderate, High, Speculative)? Return risk rating and customer count, most populated first.',
    'GROUP BY risk_rating on customers.',['SELECT','GROUP BY','COUNT','ORDER BY'],['risk_rating','customer_count'],
    "SELECT risk_rating, COUNT(id) AS customer_count FROM customers GROUP BY risk_rating ORDER BY customer_count DESC;",'t',
    ['Group customers by risk_rating.','Count customer IDs.'],'Enterprise credit risk profile illustrating customer risk segmentation.',20,4),

  q('fin-L1-028','finance',1,28,'core','Total Vault Cash Reserves by State','Rachel Adams','Director of Branch Operations',
    'Regional cash reserves: Calculate total vault cash limit and total branch count grouped by state. Order highest vault cash first.',
    'GROUP BY state on branches.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['state','total_vault_cash','branch_count'],
    "SELECT state, ROUND(SUM(vault_cash_limit), 2) AS total_vault_cash, COUNT(id) AS branch_count FROM branches GROUP BY state ORDER BY total_vault_cash DESC;",'t',
    ['Group branches by state.','Sum vault_cash_limit and count branches.'],'Quantifies regulatory vault cash holdings across state jurisdictions.',20,5),

  q('fin-L1-029','finance',1,29,'core','Transaction Volume and Dollars by Transaction Type','Victor Vance','Head of Risk & Compliance',
    'Payment rail analytics: For each transaction type (deposit, withdrawal, transfer, fee, wire), compute total transactions count and total dollar volume.',
    'GROUP BY transaction_type on transactions.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['transaction_type','tx_count','total_volume'],
    "SELECT transaction_type, COUNT(id) AS tx_count, ROUND(SUM(amount), 2) AS total_volume FROM transactions GROUP BY transaction_type ORDER BY total_volume DESC;",'t',
    ['Group transactions by transaction_type.','Count transactions and sum amount.'],'Provides operational overview of settlement volumes across payment channels.',20,5),

  q('fin-L1-030','finance',1,30,'core','Average Customer Income by Branch City','Arthur Pendleton','Chief Wealth Advisor',
    'Regional purchasing power: What is the average annual income and total customer count across each branch city? Highest average income first.',
    'GROUP BY branch_city on customers.',['SELECT','GROUP BY','AVG','COUNT','ORDER BY'],['branch_city','avg_income','customer_count'],
    "SELECT branch_city, ROUND(AVG(annual_income), 2) AS avg_income, COUNT(id) AS customer_count FROM customers GROUP BY branch_city ORDER BY avg_income DESC;",'t',
    ['Group customers by branch_city.','Compute AVG(annual_income) and COUNT(id).' ],'Identifies high-income metropolitan areas for branch footprint expansion.',20,5),

  q('fin-L1-031','finance',1,31,'core','Accounts Distribution by Operational Status','Victor Vance','Head of Risk & Compliance',
    'Depository health check: Count accounts and calculate total balance for each account status (active, frozen, closed).',
    'GROUP BY status on accounts.',['SELECT','GROUP BY','COUNT','SUM','ORDER BY'],['status','account_count','total_balance'],
    "SELECT status, COUNT(id) AS account_count, ROUND(SUM(balance), 2) AS total_balance FROM accounts GROUP BY status ORDER BY total_balance DESC;",'t',
    ['Group accounts by status.','Sum balance and count accounts.'],'Summarizes operational disposition of total bank depository accounts.',20,4),

  q('fin-L1-032','finance',1,32,'core','Average Credit Score by Risk Rating Category','Elena Rostova','VP of Retail Lending',
    'Credit score benchmarking: Calculate average credit score, minimum score, and maximum score for each customer risk rating.',
    'GROUP BY risk_rating on customers, AVG, MIN, MAX.',['SELECT','GROUP BY','AVG','MIN','MAX'],['risk_rating','avg_score','min_score','max_score'],
    "SELECT risk_rating, ROUND(AVG(credit_score), 1) AS avg_score, MIN(credit_score) AS min_score, MAX(credit_score) AS max_score FROM customers GROUP BY risk_rating ORDER BY avg_score DESC;",'t',
    ['Group by risk_rating.','Compute AVG, MIN, MAX on credit_score.'],'Validates credit scoring models against assigned customer risk ratings.',20,5),

  q('fin-L1-033','finance',1,33,'core','Total Card Daily Limits by Card Type','Elena Rostova','VP of Retail Lending',
    'Card exposure liability: For each card type, calculate total daily limits authorized and total issued cards. Order highest aggregate limit first.',
    'GROUP BY card_type on cards.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['card_type','total_daily_limit','cards_issued'],
    "SELECT card_type, ROUND(SUM(daily_limit), 2) AS total_daily_limit, COUNT(id) AS cards_issued FROM cards GROUP BY card_type ORDER BY total_daily_limit DESC;",'t',
    ['Group cards by card_type.','Sum daily_limit and count cards.'],'Measures maximum 24-hour liquidity exposure across payment card categories.',20,5),

  q('fin-L1-034','finance',1,34,'core','Merchant Category Distribution and Risk Counts','Victor Vance','Head of Risk & Compliance',
    'Merchant underwriting portfolio: How many merchants do we acquire in each business category (Grocery, Travel, Electronics, etc.)? Return category and merchant count.',
    'GROUP BY category on merchants.',['SELECT','GROUP BY','COUNT','ORDER BY'],['category','merchant_count'],
    "SELECT category, COUNT(id) AS merchant_count FROM merchants GROUP BY category ORDER BY merchant_count DESC;",'t',
    ['Group merchants by category.','Count merchant IDs.'],'Analyzes merchant business sector diversification.',20,4),

  q('fin-L1-035','finance',1,35,'core','Average Depository Balance by Account Type','Arthur Pendleton','Chief Wealth Advisor',
    'Account size metrics: Calculate the average balance and maximum single balance for each account type. Order highest average balance first.',
    'GROUP BY account_type on accounts, AVG, MAX.',['SELECT','GROUP BY','AVG','MAX','ORDER BY'],['account_type','avg_balance','max_balance'],
    "SELECT account_type, ROUND(AVG(balance), 2) AS avg_balance, ROUND(MAX(balance), 2) AS max_balance FROM accounts GROUP BY account_type ORDER BY avg_balance DESC;",'t',
    ['Group accounts by account_type.','Compute AVG(balance) and MAX(balance).' ],'Evaluates depository product balance sizes across retail and commercial tiers.',20,5),

  q('fin-L1-036','finance',1,36,'core','Branch Count by City with Vault Totals','Rachel Adams','Director of Branch Operations',
    'Municipal banking presence: Calculate total branches and combined vault cash limits grouped by city for cities with at least 1 branch.',
    'GROUP BY city on branches.',['SELECT','GROUP BY','COUNT','SUM','ORDER BY'],['city','branch_count','total_vault_limit'],
    "SELECT city, COUNT(id) AS branch_count, ROUND(SUM(vault_cash_limit), 2) AS total_vault_limit FROM branches GROUP BY city ORDER BY total_vault_limit DESC;",'t',
    ['Group branches by city.','Count branches and sum vault_cash_limit.'],'Summarizes physical branch footprint and cash staging by metropolitan market.',20,5),

  q('fin-L1-037','finance',1,37,'core','Largest Single Transactions Handled','Victor Vance','Head of Risk & Compliance',
    'Top transfer audit: What are the 15 largest individual transactions recorded in our ledger? Return id, account id, amount, transaction type, and timestamp.',
    'Query transactions ORDER BY amount DESC LIMIT 15.',['SELECT','ORDER BY','LIMIT'],['id','account_id','amount','transaction_type','created_at'],
    "SELECT id, account_id, amount, transaction_type, created_at FROM transactions ORDER BY amount DESC LIMIT 15;",'t',
    ['Order transactions by amount DESC.','Limit to top 15 records.'],'Reviews the single largest individual fund movements across the core ledger.',20,4),

  q('fin-L1-038','finance',1,38,'core','Total Customer Inflow Dollars From Deposits','Arthur Pendleton','Chief Wealth Advisor',
    'Retail deposit velocity: Calculate total dollars deposited and average deposit size across all deposit transactions in the ledger.',
    'SUM and AVG amount on transactions WHERE transaction_type = deposit.',['SELECT','SUM','AVG','WHERE'],['total_deposits','avg_deposit_amount'],
    "SELECT ROUND(SUM(amount), 2) AS total_deposits, ROUND(AVG(amount), 2) AS avg_deposit_amount FROM transactions WHERE transaction_type = 'deposit';",'f',
    ['Filter transactions where transaction_type = deposit.','Compute SUM(amount) and AVG(amount).' ],'Measures retail deposit inflow totals and standard customer deposit tickets.',20,4),

  q('fin-L1-039','finance',1,39,'core','Customer Count by Credit Score Tiers','Elena Rostova','VP of Retail Lending',
    'Underwriting scorecard: Group customers into credit tiers: Excellent (>= 750), Good (700 to 749), Fair (650 to 699), Subprime (< 650) using CASE. Return credit tier and customer count.',
    'CASE on credit_score GROUP BY credit tier.',['SELECT','CASE WHEN','GROUP BY','COUNT'],['credit_tier','customer_count'],
    "SELECT CASE WHEN credit_score >= 750 THEN 'Excellent' WHEN credit_score BETWEEN 700 AND 749 THEN 'Good' WHEN credit_score BETWEEN 650 AND 699 THEN 'Fair' ELSE 'Subprime' END AS credit_tier, COUNT(id) AS customer_count FROM customers GROUP BY (CASE WHEN credit_score >= 750 THEN 'Excellent' WHEN credit_score BETWEEN 700 AND 749 THEN 'Good' WHEN credit_score BETWEEN 650 AND 699 THEN 'Fair' ELSE 'Subprime' END) ORDER BY customer_count DESC;",'t',
    ['Group customers by credit tier using CASE statement.','Count customers in each tier.'],'Portfolio risk segmentation by FICO credit score bands.',20,6),

  q('fin-L1-040','finance',1,40,'core','Top 10 Affluent Customers by Annual Income','Arthur Pendleton','Chief Wealth Advisor',
    'Executive outreach: List the top 10 customers with the highest annual income. Show customer id, name, annual income, credit score, and branch city.',
    'Query customers ORDER BY annual_income DESC LIMIT 10.',['SELECT','ORDER BY','LIMIT'],['id','name','annual_income','credit_score','branch_city'],
    "SELECT id, name, annual_income, credit_score, branch_city FROM customers ORDER BY annual_income DESC LIMIT 10;",'t',
    ['Order customers by annual_income DESC LIMIT 10.','Select id, name, annual_income, credit_score, branch_city.'],'Identifies ultra-high-earning commercial accounts for executive relationship coverage.',20,4),

  q('fin-L1-041','finance',1,41,'core','Wire Transfer Transaction Volume by Date','Victor Vance','Head of Risk & Compliance',
    'Wire activity timeline: Calculate total wire transaction count and total wire amount grouped by transaction date (created_at::DATE). Order latest date first.',
    'GROUP BY created_at::DATE on transactions WHERE transaction_type = wire.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['tx_date','wire_count','total_wire_amount'],
    "SELECT created_at::DATE AS tx_date, COUNT(id) AS wire_count, ROUND(SUM(amount), 2) AS total_wire_amount FROM transactions WHERE transaction_type = 'wire' GROUP BY created_at::DATE ORDER BY tx_date DESC;",'t',
    ['Cast created_at to DATE and group by date.','Filter for transaction_type = wire.','Sum amount and count wires.'],'Daily wire settlement velocity tracking for daylight overdraft monitoring.',20,5),

  q('fin-L1-042','finance',1,42,'core','Total Depository Balances Held in Frozen Accounts','Victor Vance','Head of Risk & Compliance',
    'Restricted asset exposure: Calculate the total dollar balance currently locked in frozen accounts across each account type. Order highest balance first.',
    'GROUP BY account_type on accounts WHERE status = frozen.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['account_type','frozen_balance','account_count'],
    "SELECT account_type, ROUND(SUM(balance), 2) AS frozen_balance, COUNT(id) AS account_count FROM accounts WHERE status = 'frozen' GROUP BY account_type ORDER BY frozen_balance DESC;",'t',
    ['Filter WHERE status = frozen.','Group by account_type and sum balance.'],'Quantifies compliance-restricted funds by product type.',20,5),

  q('fin-L1-043','finance',1,43,'core','Active Account Balances Between $25,000 and $75,000','Arthur Pendleton','Chief Wealth Advisor',
    'Mid-market depository segment: Find all active accounts holding a balance between $25,000 and $75,000. Return account id, customer id, account type, and balance.',
    'Filter accounts WHERE balance BETWEEN 25000.00 AND 75000.00 and status = active.',['SELECT','WHERE','BETWEEN','AND'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE balance BETWEEN 25000.00 AND 75000.00 AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter accounts where balance BETWEEN 25000 AND 75000 and status = active.','Order by balance DESC.'],'Targets mid-market commercial accounts for treasury management services.',20,4),

  q('fin-L1-044','finance',1,44,'core','Average Daily Limit by Card Type and Status','Elena Rostova','VP of Retail Lending',
    'Payment card risk policy: Calculate average daily limit and total cards for each card type and status combination.',
    'GROUP BY card_type, status on cards.',['SELECT','GROUP BY','AVG','COUNT'],['card_type','status','avg_daily_limit','cards_count'],
    "SELECT card_type, status, ROUND(AVG(daily_limit), 2) AS avg_daily_limit, COUNT(id) AS cards_count FROM cards GROUP BY card_type, status ORDER BY card_type, status;",'f',
    ['Group cards by card_type and status.','Compute AVG(daily_limit) and COUNT(id).' ],'Assesses card portfolio credit limits across active and restricted statuses.',20,5),

  q('fin-L1-045','finance',1,45,'core','Total Withdrawal Outflows by Date','Victor Vance','Head of Risk & Compliance',
    'Liquidity stress testing: For transactions of type withdrawal, compute total dollars withdrawn and transaction count for each transaction date (created_at::DATE).',
    'GROUP BY created_at::DATE on transactions WHERE transaction_type = withdrawal.',['SELECT','GROUP BY','SUM','COUNT','ORDER BY'],['tx_date','withdrawal_count','total_outflow'],
    "SELECT created_at::DATE AS tx_date, COUNT(id) AS withdrawal_count, ROUND(SUM(amount), 2) AS total_outflow FROM transactions WHERE transaction_type = 'withdrawal' GROUP BY created_at::DATE ORDER BY tx_date DESC;",'t',
    ['Group transactions by date where transaction_type = withdrawal.','Sum amount and count withdrawals.'],'Monitors daily cash outflows for branch and treasury liquidity planning.',20,5),

  q('fin-L1-046','finance',1,46,'core','Branches With Average Vault Cash Above $15M','Rachel Adams','Director of Branch Operations',
    'Regional cash hub identification: List all branches where vault_cash_limit is at least $15,000,000, showing branch name, manager, and vault cash limit.',
    'Filter branches WHERE vault_cash_limit >= 15000000.00.',['SELECT','WHERE','ORDER BY'],['branch_name','manager_name','vault_cash_limit'],
    "SELECT branch_name, manager_name, vault_cash_limit FROM branches WHERE vault_cash_limit >= 15000000.00 ORDER BY vault_cash_limit DESC;",'t',
    ['Filter WHERE vault_cash_limit >= 15000000.00.','Order by vault_cash_limit DESC.'],'Identifies primary regional depository vaults managing large cash reserves.',20,4),

  q('fin-L1-047','finance',1,47,'core','Customer Registration Volume by Creation Month','Arthur Pendleton','Chief Wealth Advisor',
    'Account acquisition growth: Calculate new customer onboarding count grouped by year and month (EXTRACT(MONTH FROM created_at)). Order by month.',
    'GROUP BY EXTRACT(MONTH FROM created_at) on customers.',['SELECT','GROUP BY','COUNT','EXTRACT'],['reg_month','new_customers_count'],
    "SELECT EXTRACT(MONTH FROM created_at) AS reg_month, COUNT(id) AS new_customers_count FROM customers GROUP BY EXTRACT(MONTH FROM created_at) ORDER BY reg_month ASC;",'t',
    ['Extract month from created_at and group by month.','Count customer IDs.'],'Measures retail and commercial customer onboarding seasonality.',20,5),

  q('fin-L1-048','finance',1,48,'core','Fee Income Totals by Month','Victor Vance','Head of Risk & Compliance',
    'Non-interest income: Calculate total fee revenue generated grouped by month from transactions of type fee. Order by month.',
    'GROUP BY EXTRACT(MONTH FROM created_at) on transactions WHERE transaction_type = fee.',['SELECT','GROUP BY','SUM','EXTRACT'],['fee_month','total_fee_income'],
    "SELECT EXTRACT(MONTH FROM created_at) AS fee_month, ROUND(SUM(amount), 2) AS total_fee_income FROM transactions WHERE transaction_type = 'fee' GROUP BY EXTRACT(MONTH FROM created_at) ORDER BY fee_month ASC;",'t',
    ['Group fee transactions by month.','Sum fee amounts.'],'Tracks non-interest fee revenue generation across calendar months.',20,5),

  q('fin-L1-049','finance',1,49,'core','High Risk Merchants by Country of Operation','Victor Vance','Head of Risk & Compliance',
    'Merchant geographic risk: For merchants flagged as High_Risk, count how many operate in each country.',
    'GROUP BY country on merchants WHERE risk_level = High_Risk.',['SELECT','GROUP BY','COUNT','WHERE'],['country','high_risk_merchants_count'],
    "SELECT country, COUNT(id) AS high_risk_merchants_count FROM merchants WHERE risk_level = 'High_Risk' GROUP BY country ORDER BY high_risk_merchants_count DESC;",'t',
    ['Filter WHERE risk_level = High_Risk.','Group by country and count merchants.'],'Surfaces jurisdiction risk concentrations among high-risk merchant accounts.',20,5),

  q('fin-L1-050','finance',1,50,'core','Top 5 Branches with Largest Vault Cash Capacity','Rachel Adams','Director of Branch Operations',
    'Capital infrastructure: Identify the top 5 banking branches with the largest vault cash limits. Return branch name, city, state, manager name, and vault cash limit.',
    'Query branches ORDER BY vault_cash_limit DESC LIMIT 5.',['SELECT','ORDER BY','LIMIT'],['branch_name','city','state','manager_name','vault_cash_limit'],
    "SELECT branch_name, city, state, manager_name, vault_cash_limit FROM branches ORDER BY vault_cash_limit DESC LIMIT 5;",'t',
    ['Order branches by vault_cash_limit DESC.','Limit to top 5.'],'Recognizes premier regional depository vaults holding the highest physical cash reserves.',20,4),

  // ADVANCED 51–75: Conditional expressions, arithmetic transformations, string filters, multi-column grouping
  q('fin-L1-051','finance',1,51,'advanced','Customer Credit Score and Income Ratio Analysis','Elena Rostova','VP of Retail Lending',
    'Underwriting metric: For customers with annual income > $100,000, calculate income-to-credit-score ratio (annual_income / credit_score). Show customer name, income, credit score, and ratio.',
    'Compute annual_income / credit_score as income_credit_ratio.',['SELECT','WHERE','ARITHMETIC','ROUND'],['name','annual_income','credit_score','income_credit_ratio'],
    "SELECT name, annual_income, credit_score, ROUND(annual_income / credit_score, 2) AS income_credit_ratio FROM customers WHERE annual_income > 100000.00 ORDER BY income_credit_ratio DESC;",'t',
    ['Filter customers where annual_income > 100000.00.','Calculate annual_income / credit_score rounded to 2 decimal places.'],'Evaluates financial earning leverage relative to established creditworthiness.',25,6),

  q('fin-L1-052','finance',1,52,'advanced','Depository Account Balance Quartile Brackets','Arthur Pendleton','Chief Wealth Advisor',
    'Balance tier categorization: Classify each active account into brackets: Tier 1 ($100k+), Tier 2 ($50k-$99k), Tier 3 ($10k-$49k), Tier 4 (<$10k) using CASE. Return account id, account type, balance, and balance tier.',
    'CASE on balance on accounts WHERE status = active.',['SELECT','CASE WHEN','WHERE'],['id','account_type','balance','balance_tier'],
    "SELECT id, account_type, balance, CASE WHEN balance >= 100000.00 THEN 'Tier 1' WHEN balance BETWEEN 50000.00 AND 99999.99 THEN 'Tier 2' WHEN balance BETWEEN 10000.00 AND 49999.99 THEN 'Tier 3' ELSE 'Tier 4' END AS balance_tier FROM accounts WHERE status = 'active' ORDER BY balance DESC;",'t',
    ['Classify accounts into balance tiers using CASE WHEN.','Filter for status = active.'],'Structures commercial and retail accounts into actionable private banking tiers.',25,6),

  q('fin-L1-053','finance',1,53,'advanced','Transfer vs Wire Transaction Ratio Analysis','Victor Vance','Head of Risk & Compliance',
    'Rail volume comparison: For transactions of type transfer or wire, calculate total transaction count and average dollar value per transaction type.',
    'GROUP BY transaction_type on transactions WHERE transaction_type IN (transfer, wire).',['SELECT','GROUP BY','COUNT','AVG','WHERE'],['transaction_type','tx_count','avg_amount'],
    "SELECT transaction_type, COUNT(id) AS tx_count, ROUND(AVG(amount), 2) AS avg_amount FROM transactions WHERE transaction_type IN ('transfer', 'wire') GROUP BY transaction_type ORDER BY avg_amount DESC;",'t',
    ['Filter WHERE transaction_type IN (\'transfer\', \'wire\').','Group by transaction_type and compute COUNT and AVG.'],'Compares internal book transfers against external high-value wire transfers.',25,5),

  q('fin-L1-054','finance',1,54,'advanced','Active Card Daily Limit Utilization Potential','Elena Rostova','VP of Retail Lending',
    'Cardholder line exposure: For active cards, calculate total potential 30-day card spending (daily_limit * 30). Return card id, card type, daily limit, and monthly exposure potential.',
    'Compute daily_limit * 30 as monthly_exposure.',['SELECT','WHERE','ARITHMETIC'],['id','card_type','daily_limit','monthly_exposure'],
    "SELECT id, card_type, daily_limit, ROUND(daily_limit * 30.0, 2) AS monthly_exposure FROM cards WHERE status = 'active' ORDER BY monthly_exposure DESC;",'t',
    ['Calculate daily_limit * 30.0 for active cards.','Order by monthly_exposure DESC.'],'Models potential monthly liquidity draw against outstanding payment cards.',25,5),

  q('fin-L1-055','finance',1,55,'advanced','Customer Geographic Concentration and Risk Rating Matrix','Victor Vance','Head of Risk & Compliance',
    'Regional credit exposure: Group customers by branch_city and risk_rating. Count customer accounts in each combination where branch_city is New York, Boston, or San Francisco.',
    'GROUP BY branch_city, risk_rating WHERE branch_city IN (...).',['SELECT','GROUP BY','COUNT','WHERE','IN'],['branch_city','risk_rating','customer_count'],
    "SELECT branch_city, risk_rating, COUNT(id) AS customer_count FROM customers WHERE branch_city IN ('New York', 'Boston', 'San Francisco') GROUP BY branch_city, risk_rating ORDER BY branch_city, risk_rating;",'f',
    ['Filter for primary metropolitan cities.','Group by branch_city and risk_rating.'],'Maps metropolitan risk-rating distribution across major regional offices.',25,6),

  q('fin-L1-056','finance',1,56,'advanced','Branches Vault Limits as Share of State Total','Rachel Adams','Director of Branch Operations',
    'Branch liquidity proportion: List branches in NY and CA, showing branch name, state, and vault cash limit, ordered by vault limit descending.',
    'Filter branches WHERE state IN (NY, CA).',['SELECT','WHERE','IN','ORDER BY'],['branch_name','state','vault_cash_limit'],
    "SELECT branch_name, state, vault_cash_limit FROM branches WHERE state IN ('NY', 'CA') ORDER BY state ASC, vault_cash_limit DESC;",'f',
    ['Filter branches where state IN (\'NY\', \'CA\').','Order by state, vault_cash_limit DESC.'],'Evaluates cash distribution across high-volume commercial centers.',25,5),

  q('fin-L1-057','finance',1,57,'advanced','Depository Accounts With Balances Under Minimum Thresholds','Arthur Pendleton','Chief Wealth Advisor',
    'Low balance alerts: Find active checking or savings accounts holding less than $5,000 in balance. Show account id, customer id, account type, and balance.',
    'Filter accounts WHERE account_type IN (checking, savings) AND balance < 5000.00 and status = active.',['SELECT','WHERE','IN','AND'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE account_type IN ('checking', 'savings') AND balance < 5000.00 AND status = 'active' ORDER BY balance ASC;",'t',
    ['Filter checking and savings accounts where balance < 5000 and status = active.','Order by balance ASC.'],'Surfaces accounts subject to minimum maintenance balance fee assessments.',25,5),

  q('fin-L1-058','finance',1,58,'advanced','High Value Settlement Transactions With Specific Descriptions','Victor Vance','Head of Risk & Compliance',
    'Settlement audit: Find transactions where description contains Settlement and amount > $5,000. Return id, account id, amount, and description.',
    'Filter transactions WHERE description LIKE %Settlement% AND amount > 5000.00.',['SELECT','WHERE','LIKE','AND'],['id','account_id','amount','description'],
    "SELECT id, account_id, amount, description FROM transactions WHERE description LIKE '%Settlement%' AND amount > 5000.00 ORDER BY amount DESC;",'t',
    ['Filter WHERE description LIKE \'%Settlement%\' AND amount > 5000.00.','Order by amount DESC.'],'Audits institutional settlement transactions exceeding $5,000 thresholds.',25,5),

  q('fin-L1-059','finance',1,59,'advanced','Customer Wealth Bracket Distribution','Arthur Pendleton','Chief Wealth Advisor',
    'Wealth segmentation: Categorize customers into income brackets: Affluent ($300k+), Upper Middle ($200k-$299k), Middle ($100k-$199k), Entry (<$100k) using CASE. Return wealth tier and customer count.',
    'CASE statement on annual_income GROUP BY wealth tier.',['SELECT','CASE WHEN','GROUP BY','COUNT'],['wealth_tier','customer_count'],
    "SELECT CASE WHEN annual_income >= 300000.00 THEN 'Affluent' WHEN annual_income BETWEEN 200000.00 AND 299999.99 THEN 'Upper Middle' WHEN annual_income BETWEEN 100000.00 AND 199999.99 THEN 'Middle' ELSE 'Entry' END AS wealth_tier, COUNT(id) AS customer_count FROM customers GROUP BY (CASE WHEN annual_income >= 300000.00 THEN 'Affluent' WHEN annual_income BETWEEN 200000.00 AND 299999.99 THEN 'Upper Middle' WHEN annual_income BETWEEN 100000.00 AND 199999.99 THEN 'Middle' ELSE 'Entry' END) ORDER BY customer_count DESC;",'t',
    ['Segment annual_income using CASE.','Count customers per wealth bracket.'],'Structures customer base for targeted wealth advisory wealth products.',25,6),

  q('fin-L1-060','finance',1,60,'advanced','Active Card Limits by Risk Level and Issuer Type','Elena Rostova','VP of Retail Lending',
    'Issuer exposure: For cards with status active, calculate total daily limits and card count grouped by card_type.',
    'GROUP BY card_type on cards WHERE status = active.',['SELECT','GROUP BY','SUM','COUNT','WHERE'],['card_type','active_daily_limits','active_cards_count'],
    "SELECT card_type, ROUND(SUM(daily_limit), 2) AS active_daily_limits, COUNT(id) AS active_cards_count FROM cards WHERE status = 'active' GROUP BY card_type ORDER BY active_daily_limits DESC;",'t',
    ['Filter WHERE status = active.','Group by card_type and sum daily_limit.'],'Tracks aggregate daily settlement exposure across active payment card portfolios.',25,5),

  q('fin-L1-061','finance',1,61,'advanced','Transactions Occurring During Weekend or Specific Days','Victor Vance','Head of Risk & Compliance',
    'Off-hours ledger activity: Extract day of week (EXTRACT(DOW FROM created_at)) for all transactions and calculate transaction count and total volume for each day of the week.',
    'GROUP BY EXTRACT(DOW FROM created_at) on transactions.',['SELECT','GROUP BY','COUNT','SUM','EXTRACT'],['day_of_week','tx_count','total_volume'],
    "SELECT EXTRACT(DOW FROM created_at) AS day_of_week, COUNT(id) AS tx_count, ROUND(SUM(amount), 2) AS total_volume FROM transactions GROUP BY EXTRACT(DOW FROM created_at) ORDER BY day_of_week ASC;",'t',
    ['Extract DOW from created_at.','Compute transaction count and total dollar volume per day.'],'Monitors weekend vs weekday payment processing liquidity.',25,6),

  q('fin-L1-062','finance',1,62,'advanced','Depository Accounts in Frozen Status with Substantial Funds','Victor Vance','Head of Risk & Compliance',
    'High value freeze audit: Find all frozen accounts holding a balance of $50,000 or greater. Return account id, customer id, account type, and balance.',
    'Filter accounts WHERE status = frozen AND balance >= 50000.00.',['SELECT','WHERE','AND'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE status = 'frozen' AND balance >= 50000.00 ORDER BY balance DESC;",'t',
    ['Filter WHERE status = frozen AND balance >= 50000.00.','Order by balance DESC.'],'Audits substantial blocked deposits under legal or anti-money laundering restraint.',25,5),

  q('fin-L1-063','finance',1,63,'advanced','Merchants Categorized Under Travel or Crypto','Victor Vance','Head of Risk & Compliance',
    'Volatile sector merchant portfolio: Show merchant name, category, city, country, and risk level for merchants in Travel or Crypto categories.',
    'Filter merchants WHERE category IN (Travel, Crypto).',['SELECT','WHERE','IN'],['name','category','city','country','risk_level'],
    "SELECT name, category, city, country, risk_level FROM merchants WHERE category IN ('Travel', 'Crypto') ORDER BY category ASC, name ASC;",'f',
    ['Filter WHERE category IN (\'Travel\', \'Crypto\').','Select merchant identity and risk parameters.'],'Screens merchants in high-chargeback and high-volatility business sectors.',25,5),

  q('fin-L1-064','finance',1,64,'advanced','Customer Account Creation Trajectory for 2023','Arthur Pendleton','Chief Wealth Advisor',
    'Historical acquisition cohort: Find customers created between January 1, 2023 and June 30, 2023. Show customer id, name, branch city, and creation date.',
    'Filter customers WHERE created_at BETWEEN 2023-01-01 AND 2023-06-30.',['SELECT','WHERE','BETWEEN','AND'],['id','name','branch_city','created_at'],
    "SELECT id, name, branch_city, created_at FROM customers WHERE created_at BETWEEN '2023-01-01' AND '2023-06-30' ORDER BY created_at ASC, id ASC;",'t',
    ['Filter WHERE created_at BETWEEN \'2023-01-01\' AND \'2023-06-30\'.','Order by created_at.'],'Reviews early 2023 customer onboarding cohort demographics.',25,5),

  q('fin-L1-065','finance',1,65,'advanced','Small Value Transaction Volume and Fee Yield Potential','Victor Vance','Head of Risk & Compliance',
    'Micro-transactions: Count transactions where amount is strictly less than $100.00. Calculate total dollar amount and transaction count across all micro-transactions.',
    'Filter transactions WHERE amount < 100.00, compute COUNT and SUM.',['SELECT','COUNT','SUM','WHERE'],['micro_tx_count','total_micro_volume'],
    "SELECT COUNT(id) AS micro_tx_count, ROUND(SUM(amount), 2) AS total_micro_volume FROM transactions WHERE amount < 100.00;",'f',
    ['Filter WHERE amount < 100.00.','Calculate count and sum amount.'],'Measures retail micro-transaction frequency and interchange fee exposure.',25,4),

  q('fin-L1-066','finance',1,66,'advanced','High Balance Checking Accounts','Arthur Pendleton','Chief Wealth Advisor',
    'Commercial operating cash: Show checking accounts holding over $50,000 in liquid balance. Show account id, customer id, and balance, highest balance first.',
    'Filter accounts WHERE account_type = checking AND balance >= 50000.00 and status = active.',['SELECT','WHERE','AND'],['id','customer_id','balance'],
    "SELECT id, customer_id, balance FROM accounts WHERE account_type = 'checking' AND balance >= 50000.00 AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter accounts where account_type = checking and balance >= 50000 and status = active.','Order by balance DESC.'],'Surfaces non-interest-bearing operational checking deposits.',25,5),

  q('fin-L1-067','finance',1,67,'advanced','Customer Concentration by Branch City with Income Totals','Arthur Pendleton','Chief Wealth Advisor',
    'Metropolitan deposit capacity: For each branch city, calculate total customers, average credit score, and aggregate annual income. Order by total income descending.',
    'GROUP BY branch_city on customers, COUNT, AVG, SUM.',['SELECT','GROUP BY','COUNT','AVG','SUM','ORDER BY'],['branch_city','customer_count','avg_credit_score','total_income'],
    "SELECT branch_city, COUNT(id) AS customer_count, ROUND(AVG(credit_score), 1) AS avg_credit_score, ROUND(SUM(annual_income), 2) AS total_income FROM customers GROUP BY branch_city ORDER BY total_income DESC;",'t',
    ['Group customers by branch_city.','Compute count, avg credit score, and sum income.'],'Profiles regional customer wealth capacity by metropolitan market.',25,6),

  q('fin-L1-068','finance',1,68,'advanced','Top Limit Active Debit Cards','Elena Rostova','VP of Retail Lending',
    'Debit card ceiling: List the top 10 active debit cards (card_type = Visa_Debit) with the highest daily limits. Return card id, masked card number, and daily limit.',
    'Filter cards WHERE card_type = Visa_Debit AND status = active ORDER BY daily_limit DESC LIMIT 10.',['SELECT','WHERE','AND','ORDER BY','LIMIT'],['id','card_number_masked','daily_limit'],
    "SELECT id, card_number_masked, daily_limit FROM cards WHERE card_type = 'Visa_Debit' AND status = 'active' ORDER BY daily_limit DESC LIMIT 10;",'t',
    ['Filter for active Visa_Debit cards.','Order by daily_limit DESC LIMIT 10.'],'Identifies cardholders with highest daily ATM/point-of-sale withdrawal limits.',25,5),

  q('fin-L1-069','finance',1,69,'advanced','Branch Vault Limit Capacity Distribution Tiers','Rachel Adams','Director of Branch Operations',
    'Vault tiering: Classify branches into vault capacity tiers: Primary Fortress ($25M+), Major Hub ($15M-$24.9M), Standard Branch (<$15M) using CASE. Return branch name, state, vault limit, and vault tier.',
    'CASE on vault_cash_limit in branches table.',['SELECT','CASE WHEN','ORDER BY'],['branch_name','state','vault_cash_limit','vault_tier'],
    "SELECT branch_name, state, vault_cash_limit, CASE WHEN vault_cash_limit >= 25000000.00 THEN 'Primary Fortress' WHEN vault_cash_limit BETWEEN 15000000.00 AND 24999999.99 THEN 'Major Hub' ELSE 'Standard Branch' END AS vault_tier FROM branches ORDER BY vault_cash_limit DESC;",'t',
    ['Classify branches using CASE WHEN on vault_cash_limit.','Order by vault_cash_limit DESC.'],'Categorizes physical branch vaults into operational security tiers.',25,6),

  q('fin-L1-070','finance',1,70,'advanced','Recent High-Value Deposits Exceeding $7,000','Victor Vance','Head of Risk & Compliance',
    'Large cash intake: Retrieve transaction id, account id, amount, and timestamp for deposit transactions of $7,000 or more, sorted by amount descending.',
    'Filter transactions WHERE transaction_type = deposit AND amount >= 7000.00.',['SELECT','WHERE','AND','ORDER BY'],['id','account_id','amount','created_at'],
    "SELECT id, account_id, amount, created_at FROM transactions WHERE transaction_type = 'deposit' AND amount >= 7000.00 ORDER BY amount DESC;",'t',
    ['Filter WHERE transaction_type = deposit AND amount >= 7000.00.','Order by amount DESC.'],'Flags large cash deposits for anti-money laundering review.',25,5),

  q('fin-L1-071','finance',1,71,'advanced','Customer Risk Rating and Average Annual Income','Victor Vance','Head of Risk & Compliance',
    'Income by risk tier: For each risk rating category, calculate average annual income, minimum income, and maximum income. Order highest average income first.',
    'GROUP BY risk_rating on customers, AVG, MIN, MAX.',['SELECT','GROUP BY','AVG','MIN','MAX','ORDER BY'],['risk_rating','avg_income','min_income','max_income'],
    "SELECT risk_rating, ROUND(AVG(annual_income), 2) AS avg_income, ROUND(MIN(annual_income), 2) AS min_income, ROUND(MAX(annual_income), 2) AS max_income FROM customers GROUP BY risk_rating ORDER BY avg_income DESC;",'t',
    ['Group by risk_rating.','Compute AVG, MIN, MAX on annual_income.'],'Analyzes relationship between customer earning power and institutional risk rating.',25,5),

  q('fin-L1-072','finance',1,72,'advanced','Active Accounts with Extreme Balance Over $150,000','Arthur Pendleton','Chief Wealth Advisor',
    'Ultra-high net worth accounts: List all active accounts holding a balance of $150,000 or greater. Show account id, customer id, account type, and balance.',
    'Filter accounts WHERE balance >= 150000.00 AND status = active.',['SELECT','WHERE','AND'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE balance >= 150000.00 AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter WHERE balance >= 150000.00 and status = active.','Order by balance DESC.'],'Surfaces top depository relationships for executive wealth relationship coverage.',25,4),

  q('fin-L1-073','finance',1,73,'advanced','Transaction Volume by Specific Ledger Description Patterns','Victor Vance','Head of Risk & Compliance',
    'Reference tracking: Count transactions and calculate total dollar volume where description starts with Settlement ref. Return total count and total amount.',
    'Filter transactions WHERE description LIKE Settlement ref%, compute COUNT and SUM.',['SELECT','COUNT','SUM','WHERE','LIKE'],['settlement_tx_count','total_settled_volume'],
    "SELECT COUNT(id) AS settlement_tx_count, ROUND(SUM(amount), 2) AS total_settled_volume FROM transactions WHERE description LIKE 'Settlement ref%';",'f',
    ['Filter WHERE description LIKE \'Settlement ref%\'.','Calculate count and sum.'],'Reconciles core ledger settlement entries.',25,4),

  q('fin-L1-074','finance',1,74,'advanced','Customer Account Openings in First Quarter 2023','Arthur Pendleton','Chief Wealth Advisor',
    'Q1 2023 cohort: Find customers created between January 1, 2023 and March 31, 2023 with credit score >= 700. Return customer name, credit score, branch city, and creation date.',
    'Filter customers WHERE created_at BETWEEN 2023-01-01 AND 2023-03-31 AND credit_score >= 700.',['SELECT','WHERE','BETWEEN','AND'],['name','credit_score','branch_city','created_at'],
    "SELECT name, credit_score, branch_city, created_at FROM customers WHERE created_at BETWEEN '2023-01-01' AND '2023-03-31' AND credit_score >= 700 ORDER BY credit_score DESC;",'t',
    ['Filter for Q1 2023 customer creations with credit_score >= 700.','Order by credit_score DESC.'],'Tracks high-credit customer onboarding cohort for quarterly reviews.',25,5),

  q('fin-L1-075','finance',1,75,'advanced','Total Balance Held Across Top 20 Depository Accounts','Arthur Pendleton','Chief Wealth Advisor',
    'Depository concentration: Calculate the sum of balances across the top 20 largest active accounts. Return the top 20 accounts total balance.',
    'Subquery or derived table summing top 20 accounts by balance.',['SELECT','SUBQUERY','SUM'],['top_20_balance_sum'],
    "SELECT ROUND(SUM(balance), 2) AS top_20_balance_sum FROM (SELECT balance FROM accounts WHERE status = 'active' ORDER BY balance DESC LIMIT 20) top_accs;",'f',
    ['Order active accounts by balance DESC LIMIT 20.','Calculate SUM(balance) across the subquery.'],'Measures deposit concentration among the bank largest 20 customer accounts.',25,6),

  // BOSS / CAPSTONE 76–100: Complex multi-tier filters, subqueries, arithmetic analytics, consolidated executive summaries
  q('fin-L1-076','finance',1,76,'boss','Customer Credit Score Decile Distribution Analysis','Elena Rostova','VP of Retail Lending',
    'Underwriting portfolio review: Divide customers into credit brackets using CASE: Tier 1 (780+), Tier 2 (740-779), Tier 3 (700-739), Tier 4 (660-699), Tier 5 (<660). Calculate customer count, average annual income, and minimum income in each tier.',
    'CASE on credit_score with COUNT, AVG, MIN grouped by credit tier.',['SELECT','CASE WHEN','GROUP BY','COUNT','AVG','MIN'],['credit_bracket','customer_count','avg_income','min_income'],
    "SELECT CASE WHEN credit_score >= 780 THEN 'Tier 1' WHEN credit_score BETWEEN 740 AND 779 THEN 'Tier 2' WHEN credit_score BETWEEN 700 AND 739 THEN 'Tier 3' WHEN credit_score BETWEEN 660 AND 699 THEN 'Tier 4' ELSE 'Tier 5' END AS credit_bracket, COUNT(id) AS customer_count, ROUND(AVG(annual_income), 2) AS avg_income, ROUND(MIN(annual_income), 2) AS min_income FROM customers GROUP BY (CASE WHEN credit_score >= 780 THEN 'Tier 1' WHEN credit_score BETWEEN 740 AND 779 THEN 'Tier 2' WHEN credit_score BETWEEN 700 AND 739 THEN 'Tier 3' WHEN credit_score BETWEEN 660 AND 699 THEN 'Tier 4' ELSE 'Tier 5' END) ORDER BY credit_bracket ASC;",'t',
    ['Group customers into 5 credit brackets using CASE WHEN.','Compute count, avg income, min income.'],'Institutional credit risk distribution linking FICO bands to verified income.',30,8),

  q('fin-L1-077','finance',1,77,'boss','Depository Balance Outlier Accounts Exceeding Branch Average','Arthur Pendleton','Chief Wealth Advisor',
    'Large deposit outlier check: Find all active accounts whose balance is strictly greater than the average balance of all active accounts in the entire bank. Return account id, customer id, account type, and balance.',
    'Subquery: balance > (SELECT AVG(balance) FROM accounts WHERE status = active).',['SELECT','WHERE','SCALAR SUBQUERY'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE status = 'active' AND balance > (SELECT AVG(balance) FROM accounts WHERE status = 'active') ORDER BY balance DESC;",'t',
    ['Compute overall active account average balance in scalar subquery.','Filter accounts where balance exceeds that benchmark.'],'Isolates above-average deposit relationships contributing to liquidity reserves.',30,7),

  q('fin-L1-078','finance',1,78,'boss','Regional Branch Vault Cash Reserve Concentration Index','Rachel Adams','Director of Branch Operations',
    'Regional cash audit: For each state, calculate total vault cash limit, average vault cash limit per branch, and branch count. Filter for states having total vault cash >= $25,000,000. Order highest vault cash first.',
    'GROUP BY state on branches HAVING SUM(vault_cash_limit) >= 25000000.00.',['SELECT','GROUP BY','HAVING','SUM','AVG'],['state','branch_count','total_vault_cash','avg_vault_cash'],
    "SELECT state, COUNT(id) AS branch_count, ROUND(SUM(vault_cash_limit), 2) AS total_vault_cash, ROUND(AVG(vault_cash_limit), 2) AS avg_vault_cash FROM branches GROUP BY state HAVING SUM(vault_cash_limit) >= 25000000.00 ORDER BY total_vault_cash DESC;",'t',
    ['Group branches by state.','Filter in HAVING for SUM(vault_cash_limit) >= 25000000.00.','Order by total_vault_cash DESC.'],'Surfaces critical state jurisdictions managing heavy physical currency volume.',30,8),

  q('fin-L1-079','finance',1,79,'boss','High Value Ledger Transactions with Cumulative Share Potential','Victor Vance','Head of Risk & Compliance',
    'Large exposure ledger: Retrieve the top 20 largest transactions recorded in the ledger. Return transaction id, account id, amount, transaction type, description, and timestamp.',
    'ORDER BY amount DESC LIMIT 20 on transactions.',['SELECT','ORDER BY','LIMIT'],['id','account_id','amount','transaction_type','description','created_at'],
    "SELECT id, account_id, amount, transaction_type, description, created_at FROM transactions ORDER BY amount DESC LIMIT 20;",'t',
    ['Order transactions by amount DESC LIMIT 20.','Select full transaction detail.'],'AML inspection of the 20 largest individual transactions across the core ledger.',30,6),

  q('fin-L1-080','finance',1,80,'boss','Customer Earning and Credit Score Matrix by Metropolitan Area','Arthur Pendleton','Chief Wealth Advisor',
    'Metropolitan wealth index: For each branch city, calculate customer count, average credit score, average annual income, and total annual income. Filter for cities with customer count >= 5. Order by total income descending.',
    'GROUP BY branch_city on customers HAVING COUNT(id) >= 5.',['SELECT','GROUP BY','HAVING','COUNT','AVG','SUM'],['branch_city','customer_count','avg_credit_score','avg_income','total_income'],
    "SELECT branch_city, COUNT(id) AS customer_count, ROUND(AVG(credit_score), 1) AS avg_credit_score, ROUND(AVG(annual_income), 2) AS avg_income, ROUND(SUM(annual_income), 2) AS total_income FROM customers GROUP BY branch_city HAVING COUNT(id) >= 5 ORDER BY total_income DESC;",'t',
    ['Group customers by branch_city.','Filter HAVING COUNT(id) >= 5.','Compute customer count, avg score, avg income, total income.'],'Evaluates metropolitan market wealth clusters for commercial lending and wealth offices.',30,8),

  q('fin-L1-081','finance',1,81,'boss','Card Portfolio Aggregate Exposure by Card Type and Status','Elena Rostova','VP of Retail Lending',
    'Card exposure scorecard: Calculate total daily limits, average daily limit, and total card count grouped by card_type and status. Order by total daily limit descending.',
    'GROUP BY card_type, status on cards, SUM, AVG, COUNT.',['SELECT','GROUP BY','SUM','AVG','COUNT','ORDER BY'],['card_type','status','total_limit','avg_daily_limit','cards_count'],
    "SELECT card_type, status, ROUND(SUM(daily_limit), 2) AS total_limit, ROUND(AVG(daily_limit), 2) AS avg_daily_limit, COUNT(id) AS cards_count FROM cards GROUP BY card_type, status ORDER BY total_limit DESC;",'t',
    ['Group cards by card_type and status.','Calculate sum, avg, and count.','Order by total_limit DESC.'],'Comprehensive card portfolio exposure report balancing credit lines against card status.',30,7),

  q('fin-L1-082','finance',1,82,'boss','Depository Balances Stratification Across Active Account Classes','Arthur Pendleton','Chief Wealth Advisor',
    'Product profitability summary: For each account type where status is active, calculate total balance, average balance, minimum balance, and maximum balance. Order by total balance descending.',
    'GROUP BY account_type on accounts WHERE status = active, SUM, AVG, MIN, MAX.',['SELECT','GROUP BY','SUM','AVG','MIN','MAX','ORDER BY'],['account_type','total_balance','avg_balance','min_balance','max_balance'],
    "SELECT account_type, ROUND(SUM(balance), 2) AS total_balance, ROUND(AVG(balance), 2) AS avg_balance, ROUND(MIN(balance), 2) AS min_balance, ROUND(MAX(balance), 2) AS max_balance FROM accounts WHERE status = 'active' GROUP BY account_type ORDER BY total_balance DESC;",'t',
    ['Filter accounts for status = active.','Group by account_type.','Compute SUM, AVG, MIN, MAX on balance.'],'Depository balance matrix detailing asset size variance across core banking products.',30,7),

  q('fin-L1-083','finance',1,83,'boss','Wire and Transfer Outflows Exceeding Daily Thresholds','Victor Vance','Head of Risk & Compliance',
    'Outflow risk screening: Find all transactions of type wire or transfer where amount >= $6,000. Return transaction id, account id, amount, transaction type, and timestamp, ordered by amount descending.',
    'Filter transactions WHERE transaction_type IN (wire, transfer) AND amount >= 6000.00.',['SELECT','WHERE','IN','AND','ORDER BY'],['id','account_id','amount','transaction_type','created_at'],
    "SELECT id, account_id, amount, transaction_type, created_at FROM transactions WHERE transaction_type IN ('wire', 'transfer') AND amount >= 6000.00 ORDER BY amount DESC;",'t',
    ['Filter WHERE transaction_type IN (\'wire\', \'transfer\') AND amount >= 6000.00.','Order by amount DESC.'],'High-dollar liquidity outflow screening for fraudulent transfer interception.',30,6),

  q('fin-L1-084','finance',1,84,'boss','High Income Customers with Moderate or Low Risk Ratings','Arthur Pendleton','Chief Wealth Advisor',
    'Preferred private wealth prospects: Find customers with annual income >= $250,000 and risk_rating IN (Low, Moderate). Return customer id, name, annual income, credit score, and risk rating.',
    'Filter customers WHERE annual_income >= 250000.00 AND risk_rating IN (Low, Moderate).',['SELECT','WHERE','IN','AND','ORDER BY'],['id','name','annual_income','credit_score','risk_rating'],
    "SELECT id, name, annual_income, credit_score, risk_rating FROM customers WHERE annual_income >= 250000.00 AND risk_rating IN ('Low', 'Moderate') ORDER BY annual_income DESC;",'t',
    ['Filter WHERE annual_income >= 250000.00 AND risk_rating IN (\'Low\', \'Moderate\').','Order by annual_income DESC.'],'Surfaces affluent, low-risk clients for bespoke wealth management and lending.',30,6),

  q('fin-L1-085','finance',1,85,'boss','Merchant Category Risk and Geography Profile','Victor Vance','Head of Risk & Compliance',
    'Merchant underwriting portfolio: Group merchants by category and risk_level. Count total merchants in each combination. Order by category and merchant count descending.',
    'GROUP BY category, risk_level on merchants.',['SELECT','GROUP BY','COUNT','ORDER BY'],['category','risk_level','merchant_count'],
    "SELECT category, risk_level, COUNT(id) AS merchant_count FROM merchants GROUP BY category, risk_level ORDER BY category ASC, merchant_count DESC;",'t',
    ['Group merchants by category and risk_level.','Count merchant accounts.'],'Examines merchant acquiring portfolio risk profiles by commerce vertical.',30,6),

  q('fin-L1-086','finance',1,86,'boss','Branch Vault Utilization Density by Regional Office','Rachel Adams','Director of Branch Operations',
    'Vault cash distribution: Rank all regional branches by vault cash limit descending. Return branch name, city, state, manager name, and vault cash limit.',
    'Query branches ORDER BY vault_cash_limit DESC.',['SELECT','ORDER BY'],['branch_name','city','state','manager_name','vault_cash_limit'],
    "SELECT branch_name, city, state, manager_name, vault_cash_limit FROM branches ORDER BY vault_cash_limit DESC;",'t',
    ['Order all branches by vault_cash_limit DESC.','Select full branch metadata.'],'Comprehensive physical vault cash reserve listing for central treasury management.',30,5),

  q('fin-L1-087','finance',1,87,'boss','Depository Balance Ratio: Active vs Frozen Accounts','Victor Vance','Head of Risk & Compliance',
    'Liquidity availability ratio: Compute total balance held in active accounts vs total balance held in frozen accounts using conditional SUM(CASE). Return active balance, frozen balance, and total depository balance.',
    'Conditional SUM(CASE WHEN status = active) and SUM(CASE WHEN status = frozen).',['SELECT','SUM CASE','ARITHMETIC'],['active_balance','frozen_balance','total_depository_balance'],
    "SELECT ROUND(SUM(CASE WHEN status = 'active' THEN balance ELSE 0 END), 2) AS active_balance, ROUND(SUM(CASE WHEN status = 'frozen' THEN balance ELSE 0 END), 2) AS frozen_balance, ROUND(SUM(balance), 2) AS total_depository_balance FROM accounts;",'f',
    ['Use conditional SUM(CASE) to separate active and frozen balances.','Compute grand total balance.'],'Quantifies available operational depository liquidity vs legally restricted funds.',30,7),

  q('fin-L1-088','finance',1,88,'boss','Transactions Aggregate Outflow vs Inflow Balance','Victor Vance','Head of Risk & Compliance',
    'Net cash flow audit: Calculate total inflow volume (deposits) vs total outflow volume (withdrawals, transfers, fees, wires) across all ledger transactions using conditional SUM(CASE). Return total inflows, total outflows, and net cash movement.',
    'Conditional SUM(CASE) on transaction_type to compute inflows vs outflows.',['SELECT','SUM CASE','ARITHMETIC'],['total_inflows','total_outflows','net_cash_movement'],
    "SELECT ROUND(SUM(CASE WHEN transaction_type = 'deposit' THEN amount ELSE 0 END), 2) AS total_inflows, ROUND(SUM(CASE WHEN transaction_type != 'deposit' THEN amount ELSE 0 END), 2) AS total_outflows, ROUND(SUM(CASE WHEN transaction_type = 'deposit' THEN amount ELSE -amount END), 2) AS net_cash_movement FROM transactions;",'f',
    ['Sum deposits as total_inflows.','Sum non-deposits as total_outflows.','Compute net cash movement.'],'Institutional ledger reconciliation balancing overall cash inflows against customer outflows.',30,8),

  q('fin-L1-089','finance',1,89,'boss','Customer Credit Score and Annual Income Deciles','Elena Rostova','VP of Retail Lending',
    'Credit score decile analysis: Find all customers with credit score >= 700 and annual income >= $200,000. Return customer name, credit score, annual income, branch city, and risk rating, ordered by credit score descending.',
    'Filter customers WHERE credit_score >= 700 AND annual_income >= 200000.00.',['SELECT','WHERE','AND','ORDER BY'],['name','credit_score','annual_income','branch_city','risk_rating'],
    "SELECT name, credit_score, annual_income, branch_city, risk_rating FROM customers WHERE credit_score >= 700 AND annual_income >= 200000.00 ORDER BY credit_score DESC, annual_income DESC;",'t',
    ['Filter WHERE credit_score >= 700 AND annual_income >= 200000.00.','Order by credit_score DESC, annual_income DESC.'],'Surfaces prime affluent retail customers eligible for jumbo mortgages and premium lines.',30,6),

  q('fin-L1-090','finance',1,90,'boss','Card Daily Limits Exceeding Standard Retail Ceiling','Elena Rostova','VP of Retail Lending',
    'Card portfolio risk ceiling: Find all active cards with daily limit strictly greater than $7,500. Return card id, card type, masked card number, and daily limit, ordered by limit descending.',
    'Filter cards WHERE daily_limit > 7500.00 AND status = active.',['SELECT','WHERE','AND','ORDER BY'],['id','card_type','card_number_masked','daily_limit'],
    "SELECT id, card_type, card_number_masked, daily_limit FROM cards WHERE daily_limit > 7500.00 AND status = 'active' ORDER BY daily_limit DESC;",'t',
    ['Filter WHERE daily_limit > 7500.00 AND status = active.','Order by daily_limit DESC.'],'Monitors high-exposure debit and credit card issuing facilities.',30,5),

  q('fin-L1-091','finance',1,91,'boss','Branch Network Summary by State and City','Rachel Adams','Director of Branch Operations',
    'Regional network hierarchy: Calculate total branches, total vault cash limit, and average vault cash limit for each state and city. Order by state, city.',
    'GROUP BY state, city on branches, COUNT, SUM, AVG.',['SELECT','GROUP BY','COUNT','SUM','AVG','ORDER BY'],['state','city','branch_count','total_vault_cash','avg_vault_cash'],
    "SELECT state, city, COUNT(id) AS branch_count, ROUND(SUM(vault_cash_limit), 2) AS total_vault_cash, ROUND(AVG(vault_cash_limit), 2) AS avg_vault_cash FROM branches GROUP BY state, city ORDER BY state ASC, city ASC;",'t',
    ['Group branches by state and city.','Compute branch count, total vault cash, and avg vault cash.'],'Comprehensive branch infrastructure summary across metropolitan banking centers.',30,7),

  q('fin-L1-092','finance',1,92,'boss','Active Accounts Holding Greater Than Median Balance','Arthur Pendleton','Chief Wealth Advisor',
    'Depository core percentile check: Find all active accounts with balance greater than $50,000. Return account id, customer id, account type, and balance, ordered by balance descending.',
    'Filter accounts WHERE balance > 50000.00 and status = active.',['SELECT','WHERE','AND','ORDER BY'],['id','customer_id','account_type','balance'],
    "SELECT id, customer_id, account_type, balance FROM accounts WHERE balance > 50000.00 AND status = 'active' ORDER BY balance DESC;",'t',
    ['Filter accounts where balance > 50000 and status = active.','Order by balance DESC.'],'Isolates key funding relationships driving core bank liquidity reserves.',30,5),

  q('fin-L1-093','finance',1,93,'boss','Wire Transactions Volume Aggregated by Day of Week','Victor Vance','Head of Risk & Compliance',
    'Payment rail timing: For transactions of type wire, calculate wire transaction count, total dollar volume, and average wire amount for each day of the week (EXTRACT(DOW FROM created_at)).',
    'GROUP BY EXTRACT(DOW FROM created_at) on transactions WHERE transaction_type = wire.',['SELECT','GROUP BY','COUNT','SUM','AVG','EXTRACT'],['day_of_week','wire_count','total_wire_volume','avg_wire_amount'],
    "SELECT EXTRACT(DOW FROM created_at) AS day_of_week, COUNT(id) AS wire_count, ROUND(SUM(amount), 2) AS total_wire_volume, ROUND(AVG(amount), 2) AS avg_wire_amount FROM transactions WHERE transaction_type = 'wire' GROUP BY EXTRACT(DOW FROM created_at) ORDER BY day_of_week ASC;",'t',
    ['Filter for transaction_type = wire.','Extract DOW and compute count, sum, avg.'],'Tracks institutional wire flow patterns across the weekly banking cycle.',30,7),

  q('fin-L1-094','finance',1,94,'boss','Customer Credit Risk and Earning Capacity Profile','Victor Vance','Head of Risk & Compliance',
    'Credit risk underwriting review: Calculate total customers, average credit score, and average annual income for each customer risk rating where customer count >= 10. Order by avg credit score descending.',
    'GROUP BY risk_rating on customers HAVING COUNT(id) >= 10.',['SELECT','GROUP BY','HAVING','COUNT','AVG','ORDER BY'],['risk_rating','customer_count','avg_credit_score','avg_income'],
    "SELECT risk_rating, COUNT(id) AS customer_count, ROUND(AVG(credit_score), 1) AS avg_credit_score, ROUND(AVG(annual_income), 2) AS avg_income FROM customers GROUP BY risk_rating HAVING COUNT(id) >= 10 ORDER BY avg_credit_score DESC;",'t',
    ['Group customers by risk_rating.','Filter HAVING COUNT(id) >= 10.','Compute count, avg credit score, avg annual income.'],'Evaluates credit scoring consistency and income underwriting by risk grade.',30,7),

  q('fin-L1-095','finance',1,95,'boss','Top 15 Most Active Merchant Accounts by City and Risk','Victor Vance','Head of Risk & Compliance',
    'Merchant roster: List merchant name, category, city, country, and risk level for all merchants in standard or high-risk categories, ordered by risk level descending and merchant name.',
    'Filter merchants ORDER BY risk_level DESC, name ASC LIMIT 15.',['SELECT','ORDER BY','LIMIT'],['name','category','city','country','risk_level'],
    "SELECT name, category, city, country, risk_level FROM merchants ORDER BY risk_level DESC, name ASC LIMIT 15;",'t',
    ['Order merchants by risk_level DESC, name ASC.','Limit to top 15.'],'Commercial merchant underwriting directory identifying elevated risk counterparties.',30,5),

  q('fin-L1-096','finance',1,96,'boss','Total Depository Balances Grouped by Balance Size Tiers','Arthur Pendleton','Chief Wealth Advisor',
    'Balance tier summary: Group active accounts into balance tiers: Premium ($100k+), Standard ($25k-$99k), Entry (<$25k) using CASE. Calculate total dollar balance and account count in each tier.',
    'CASE on balance on accounts WHERE status = active, SUM, COUNT.',['SELECT','CASE WHEN','GROUP BY','SUM','COUNT'],['balance_tier','total_balance','account_count'],
    "SELECT CASE WHEN balance >= 100000.00 THEN 'Premium ($100k+)' WHEN balance BETWEEN 25000.00 AND 99999.99 THEN 'Standard ($25k-$99k)' ELSE 'Entry (<$25k)' END AS balance_tier, ROUND(SUM(balance), 2) AS total_balance, COUNT(id) AS account_count FROM accounts WHERE status = 'active' GROUP BY (CASE WHEN balance >= 100000.00 THEN 'Premium ($100k+)' WHEN balance BETWEEN 25000.00 AND 99999.99 THEN 'Standard ($25k-$99k)' ELSE 'Entry (<$25k)' END) ORDER BY total_balance DESC;",'t',
    ['Classify accounts using CASE WHEN.','Sum balance and count accounts per balance bracket.'],'Strategic deposit stratification illustrating concentration of retail and commercial deposits.',30,8),

  q('fin-L1-097','finance',1,97,'boss','Cash Inflows vs Outflows for Largest Transaction Dates','Victor Vance','Head of Risk & Compliance',
    'Daily net ledger settlement: For each transaction date (created_at::DATE), calculate total transaction count and net volume (deposits positive, all other types negative). Order by net volume descending LIMIT 15.',
    'GROUP BY created_at::DATE with conditional SUM(CASE).',['SELECT','GROUP BY','SUM CASE','COUNT','ORDER BY','LIMIT'],['tx_date','tx_count','net_settlement_volume'],
    "SELECT created_at::DATE AS tx_date, COUNT(id) AS tx_count, ROUND(SUM(CASE WHEN transaction_type = 'deposit' THEN amount ELSE -amount END), 2) AS net_settlement_volume FROM transactions GROUP BY created_at::DATE ORDER BY net_settlement_volume DESC LIMIT 15;",'t',
    ['Group transactions by date.','Sum deposits as positive and non-deposits as negative.','Order by net_settlement_volume DESC LIMIT 15.'],'Identifies dates with top positive liquidity accretion in the central ledger.',30,8),

  q('fin-L1-098','finance',1,98,'boss','Top 10 High Limit Credit and Charge Cards Active in Portfolio','Elena Rostova','VP of Retail Lending',
    'Top credit limits: Find the 10 active cards with the largest daily limits. Return card id, card type, masked card number, and daily limit, ordered by daily limit descending.',
    'Filter cards WHERE status = active ORDER BY daily_limit DESC LIMIT 10.',['SELECT','WHERE','ORDER BY','LIMIT'],['id','card_type','card_number_masked','daily_limit'],
    "SELECT id, card_type, card_number_masked, daily_limit FROM cards WHERE status = 'active' ORDER BY daily_limit DESC LIMIT 10;",'t',
    ['Filter active cards.','Order by daily_limit DESC LIMIT 10.'],'Surfaces the highest single-card transactional limits authorized on active accounts.',30,5),

  q('fin-L1-099','finance',1,99,'boss','Total Inactive and Frozen Depository Balances Exposure','Victor Vance','Head of Risk & Compliance',
    'Restricted capital audit: Calculate total balance, account count, and average balance for all accounts that are NOT active (status != active).',
    'Filter accounts WHERE status != active, compute SUM, COUNT, AVG.',['SELECT','SUM','COUNT','AVG','WHERE'],['non_active_accounts_count','total_restricted_balance','avg_restricted_balance'],
    "SELECT COUNT(id) AS non_active_accounts_count, ROUND(SUM(balance), 2) AS total_restricted_balance, ROUND(AVG(balance), 2) AS avg_restricted_balance FROM accounts WHERE status != 'active';",'f',
    ['Filter WHERE status != active.','Calculate COUNT, SUM, and AVG on balance.'],'Measures total restricted and dormant funds under institutional hold.',30,6),

  q('fin-L1-100','finance',1,100,'boss','The Grand Level 1 Bank Executive Operations Dashboard','Arthur Pendleton','Chief Wealth Advisor',
    'Final Level 1 Challenge: Consolidated Bank Balance Sheet & Operational Health Card — Calculate: (1) Total active regional branches, (2) Total registered bank customers, (3) Total active depository accounts, (4) Grand total depository balance across active accounts, and (5) Grand total vault cash limit authorized across all branches. Return all five key metrics in a single row.',
    'Consolidated cross-table financial KPI dashboard using scalar subqueries.',['SELECT','SCALAR SUBQUERY','COUNT','SUM'],['total_active_branches','total_customers','total_active_accounts','total_active_depository_balance','total_vault_cash_authorized'],
    "SELECT (SELECT COUNT(id) FROM branches) AS total_active_branches, (SELECT COUNT(id) FROM customers) AS total_customers, (SELECT COUNT(id) FROM accounts WHERE status = 'active') AS total_active_accounts, (SELECT ROUND(SUM(balance), 2) FROM accounts WHERE status = 'active') AS total_active_depository_balance, (SELECT ROUND(SUM(vault_cash_limit), 2) FROM branches) AS total_vault_cash_authorized;",'f',
    ['Combine 5 scalar subqueries querying branches, customers, and accounts.','Return unified single-row executive banking health scorecard.'],'Grand Level 1 Capstone Dashboard: Synthesizes core depository balances, customer base scale, and regional branch cash reserves into a premier executive state-of-the-bank summary.',30,12)
];

const outPath = path.resolve(__dirname, '../src/lib/content/fin-l1-questions.ts');
const fileContent = `import { QuestionDefinition } from "./ecom-l1-questions";

export const FIN_L1_QUESTIONS: QuestionDefinition[] = ${JSON.stringify(L1, null, 2)};
`;

fs.writeFileSync(outPath, fileContent, 'utf-8');
console.log('Successfully generated FIN_L1_QUESTIONS: ' + L1.length + ' questions.');
