const fs = require('fs');
const path = require('path');

const personas = [
  { name: 'Samira Khan', role: 'CEO & Founder' },
  { name: 'Tariq Mansoor', role: 'VP of Engineering & Cloud Ops' },
  { name: 'Chloe Vance', role: 'Head of Product Analytics & CS' },
];

const l2Templates = [
  {
    authorIdx: 0,
    title: "Total MRR Contribution by Industry Vertical",
    desc: "Samira here. Ahead of our board meeting, calculate the total active monthly recurring revenue generated by each customer industry. Show industry, active subscriber count, and total_mrr rounded to 2 decimals, ordered by total_mrr descending.",
    sql: "SELECT a.industry, COUNT(s.id) AS subscriber_count, ROUND(SUM(s.mrr), 2) AS total_mrr FROM accounts a JOIN subscriptions s ON a.id = s.account_id WHERE s.status = 'active' GROUP BY a.industry ORDER BY total_mrr DESC;",
    cols: ["industry", "subscriber_count", "total_mrr"],
    hint: "Join accounts and subscriptions with WHERE s.status = 'active' and group by a.industry.",
    context: "Industry vertical MRR concentration and market penetration.",
    concepts: ["INNER JOIN", "WHERE", "GROUP BY", "SUM()", "COUNT()"],
    difficulty: "medium"
  },
  {
    authorIdx: 2,
    title: "Support Ticket Resolution Time by Priority",
    desc: "Chloe here from Customer Success. We need an SLA audit. For each support ticket priority level, calculate the total tickets logged and average resolution hours rounded to 1 decimal place, ordered by average resolution hours descending.",
    sql: "SELECT priority, COUNT(id) AS ticket_count, ROUND(AVG(resolution_hours), 1) AS avg_resolution_hours FROM support_tickets GROUP BY priority ORDER BY avg_resolution_hours DESC;",
    cols: ["priority", "ticket_count", "avg_resolution_hours"],
    hint: "Group support_tickets by priority and compute COUNT(id) and AVG(resolution_hours).",
    context: "SLA compliance and ticket turnaround benchmarks.",
    concepts: ["GROUP BY", "AVG()", "COUNT()", "ROUND()"],
    difficulty: "warm-up"
  },
  {
    authorIdx: 1,
    title: "Cloud Infrastructure Hosting Costs by Cloud Provider",
    desc: "Tariq from Cloud Ops. Summarize our cloud infrastructure spend. Show cloud_provider, count of active clusters as cluster_count, and total monthly cost (sum of monthly_cost_usd), ordered by total cost descending.",
    sql: "SELECT cloud_provider, COUNT(id) AS cluster_count, ROUND(SUM(monthly_cost_usd), 2) AS total_monthly_cost FROM cloud_clusters GROUP BY cloud_provider ORDER BY total_monthly_cost DESC;",
    cols: ["cloud_provider", "cluster_count", "total_monthly_cost"],
    hint: "Group cloud_clusters by cloud_provider and compute COUNT and SUM of monthly_cost_usd.",
    context: "Multi-cloud hosting footprint and infrastructure cost management.",
    concepts: ["GROUP BY", "SUM()", "COUNT()", "ROUND()"],
    difficulty: "warm-up"
  },
  {
    authorIdx: 2,
    title: "High-Volume Feature Usage by Account Tier",
    desc: "Chloe here. Which account tiers drive the most product usage? Join accounts and feature_usage to calculate total monthly events per tier. Show tier, count of tracked events, and total monthly events, ordered by total events descending.",
    sql: "SELECT a.tier, COUNT(fu.id) AS feature_entries, SUM(fu.monthly_events) AS total_monthly_events FROM accounts a JOIN feature_usage fu ON a.id = fu.account_id GROUP BY a.tier ORDER BY total_monthly_events DESC;",
    cols: ["tier", "feature_entries", "total_monthly_events"],
    hint: "Join accounts to feature_usage and group by a.tier.",
    context: "Tier-based product engagement and feature adoption volume.",
    concepts: ["INNER JOIN", "GROUP BY", "SUM()", "COUNT()"],
    difficulty: "medium"
  },
  {
    authorIdx: 0,
    title: "Accounts with Open Urgent Support Tickets (HAVING)",
    desc: "Samira here. Flag any enterprise customer accounts that have more than 1 open support ticket with 'critical' or 'high' priority. Display company_name, tier, and count of urgent tickets.",
    sql: "SELECT a.company_name, a.tier, COUNT(st.id) AS urgent_ticket_count FROM accounts a JOIN support_tickets st ON a.id = st.account_id WHERE st.priority IN ('critical', 'high') AND st.status = 'open' GROUP BY a.company_name, a.tier HAVING COUNT(st.id) > 1 ORDER BY urgent_ticket_count DESC;",
    cols: ["company_name", "tier", "urgent_ticket_count"],
    hint: "Join accounts and support_tickets, filter for high/critical open tickets, and use HAVING COUNT(st.id) > 1.",
    context: "Executive customer escalation and churn risk prevention.",
    concepts: ["INNER JOIN", "WHERE", "GROUP BY", "HAVING", "COUNT()"],
    difficulty: "medium"
  },
  {
    authorIdx: 1,
    title: "Cloud Clusters by Region in AWS and GCP",
    desc: "Tariq here. For each cloud region hosting our clusters in AWS or GCP, calculate total monthly spend. Return cloud_provider, region, and total_cost, ordered by total_cost descending.",
    sql: "SELECT cloud_provider, region, SUM(monthly_cost_usd) AS total_cost FROM cloud_clusters WHERE cloud_provider IN ('AWS', 'GCP') GROUP BY cloud_provider, region ORDER BY total_cost DESC;",
    cols: ["cloud_provider", "region", "total_cost"],
    hint: "Filter cloud_clusters with WHERE cloud_provider IN ('AWS', 'GCP') and group by provider and region.",
    context: "Regional cloud infrastructure deployment and expenditure.",
    concepts: ["WHERE", "IN", "GROUP BY", "SUM()"],
    difficulty: "medium"
  },
  {
    authorIdx: 2,
    title: "Top 5 Most Used Features Across Platform",
    desc: "Chloe here. Identify our 5 most heavily used product features across all customers. Show feature_name, participating account count, and sum of monthly_events, ordered highest events first.",
    sql: "SELECT feature_name, COUNT(account_id) AS account_count, SUM(monthly_events) AS total_events FROM feature_usage GROUP BY feature_name ORDER BY total_events DESC LIMIT 5;",
    cols: ["feature_name", "account_count", "total_events"],
    hint: "Group feature_usage by feature_name and take top 5.",
    context: "Product roadmap prioritizing core telemetry usage.",
    concepts: ["GROUP BY", "SUM()", "COUNT()", "LIMIT"],
    difficulty: "warm-up"
  },
  {
    authorIdx: 0,
    title: "Total Invoiced Revenue Realization per Account",
    desc: "Calculate total paid revenue and total invoices settled for each customer account. Join accounts and invoices to show company_name, tier, settled invoice count, and total_paid_amount, ordered by total paid descending.",
    sql: "SELECT a.company_name, a.tier, COUNT(i.id) AS paid_invoices_count, ROUND(SUM(i.amount), 2) AS total_paid_amount FROM accounts a JOIN invoices i ON a.id = i.account_id WHERE i.is_paid = TRUE GROUP BY a.company_name, a.tier ORDER BY total_paid_amount DESC;",
    cols: ["company_name", "tier", "paid_invoices_count", "total_paid_amount"],
    hint: "Join accounts and invoices filtering for is_paid = TRUE, grouping by account.",
    context: "Customer lifetime billed revenue realization.",
    concepts: ["INNER JOIN", "WHERE", "GROUP BY", "SUM()"],
    difficulty: "medium"
  },
  {
    authorIdx: 1,
    title: "Average User Seats per Account by Tier",
    desc: "Tariq here. How many user seats do accounts typically provision? Join accounts and users to calculate the average number of users per account across each tier. Display tier, total users, and average user count rounded to 1 decimal place.",
    sql: "SELECT a.tier, COUNT(u.id) AS total_users, ROUND(COUNT(u.id)::NUMERIC / COUNT(DISTINCT a.id), 1) AS avg_users_per_account FROM accounts a LEFT JOIN users u ON a.id = u.account_id GROUP BY a.tier ORDER BY avg_users_per_account DESC;",
    cols: ["tier", "total_users", "avg_users_per_account"],
    hint: "Join accounts and users, computing total users and ratio of users to distinct accounts.",
    context: "Seat-based pricing expansion modeling.",
    concepts: ["LEFT JOIN", "GROUP BY", "COUNT()", "Arithmetic Expressions"],
    difficulty: "medium"
  },
  {
    authorIdx: 2,
    title: "Support Ticket Backlog by Status and Priority",
    desc: "Chloe here. Break down our customer support backlog. Show status, priority, and count of tickets, ordered by status, then count descending.",
    sql: "SELECT status, priority, COUNT(id) AS ticket_count FROM support_tickets GROUP BY status, priority ORDER BY status ASC, ticket_count DESC;",
    cols: ["status", "priority", "ticket_count"],
    hint: "Group support_tickets by status and priority.",
    context: "Customer support queue triage and backlog analysis.",
    concepts: ["GROUP BY", "COUNT()", "ORDER BY"],
    difficulty: "warm-up"
  }
];

// Generate 90 additional programmatic templates across all Level 2 SaaS tables
const saasL2Combinations = [
  { tableA: "accounts", tableB: "subscriptions", joinCol: "account_id", keyA: "company_name", metricB: "mrr", title: "Account Monthly Recurring Revenue" },
  { tableA: "accounts", tableB: "feature_usage", joinCol: "account_id", keyA: "company_name", metricB: "monthly_events", title: "Account Monthly Feature Telemetry" },
  { tableA: "accounts", tableB: "invoices", joinCol: "account_id", keyA: "company_name", metricB: "amount", title: "Account Total Billing History" },
  { tableA: "accounts", tableB: "support_tickets", joinCol: "account_id", keyA: "company_name", metricB: "resolution_hours", title: "Account Support Resolution Effort" },
  { tableA: "cloud_clusters", tableB: "cloud_clusters", joinCol: "id", keyA: "cloud_provider", metricB: "monthly_cost_usd", title: "Cloud Provider Spend Aggregation" }
];

let counter = l2Templates.length;
for (let i = 0; counter < 100; i++) {
  const combo = saasL2Combinations[i % saasL2Combinations.length];
  const p = personas[counter % personas.length];
  const qNum = counter + 1;

  if (combo.tableA === combo.tableB) {
    l2Templates.push({
      authorIdx: counter % personas.length,
      title: `SaaS Infrastructure Metric #${qNum}: ${combo.title}`,
      desc: `For each cloud provider, calculate total clusters and total monthly hosting cost. Show cloud_provider, count of clusters, and total_cost rounded to 2 decimals, ordered by total_cost descending.`,
      sql: `SELECT cloud_provider, COUNT(id) AS cluster_count, ROUND(SUM(monthly_cost_usd), 2) AS total_cost FROM cloud_clusters GROUP BY cloud_provider ORDER BY total_cost DESC;`,
      cols: ["cloud_provider", "cluster_count", "total_cost"],
      hint: `Group cloud_clusters by cloud_provider and aggregate with COUNT() and SUM().`,
      context: `Infrastructure cost analysis across cloud providers.`,
      concepts: ["GROUP BY", "SUM()", "COUNT()"],
      difficulty: "medium"
    });
  } else {
    l2Templates.push({
      authorIdx: counter % personas.length,
      title: `SaaS Relational Metric #${qNum}: ${combo.title}`,
      desc: `For each ${combo.keyA} in ${combo.tableA}, compute total records and sum of ${combo.metricB} from ${combo.tableB}. Show ${combo.keyA}, total count of items, and sum of ${combo.metricB} rounded to 2 decimals, ordered by sum descending.`,
      sql: `SELECT a.${combo.keyA}, COUNT(b.id) AS total_count, ROUND(SUM(b.${combo.metricB}), 2) AS total_${combo.metricB} FROM ${combo.tableA} a JOIN ${combo.tableB} b ON a.id = b.${combo.joinCol} GROUP BY a.${combo.keyA} ORDER BY total_${combo.metricB} DESC;`,
      cols: [combo.keyA, "total_count", `total_${combo.metricB}`],
      hint: `Join ${combo.tableA} to ${combo.tableB} on a.id = b.${combo.joinCol} and group by a.${combo.keyA}.`,
      context: `Cross-entity relational SaaS metrics between ${combo.tableA} and ${combo.tableB}.`,
      concepts: ["INNER JOIN", "GROUP BY", "SUM()", "COUNT()"],
      difficulty: "medium"
    });
  }
  counter++;
}

const outQuestions = l2Templates.slice(0, 100).map((t, idx) => {
  const p = personas[t.authorIdx];
  const qNum = idx + 1;
  const pad = String(qNum).padStart(3, '0');
  return `  {
    id: "saas-L2-${pad}",
    domain: "saas",
    level: 2,
    order: ${qNum},
    difficulty: "${t.difficulty}",
    title: "${t.title.replace(/"/g, '\\"')}",
    stakeholder: {
      name: "${p.name}",
      role: "${p.role}"
    },
    request: "${t.desc.replace(/"/g, '\\"')}",
    context_notes: "${t.context.replace(/"/g, '\\"')}",
    concepts: ${JSON.stringify(t.concepts)},
    expected_columns: ${JSON.stringify(t.cols)},
    reference_sql: "${t.sql.replace(/"/g, '\\"')}",
    validation: {
      order_sensitive: false,
      column_names_sensitive: false,
      numeric_tolerance: 0
    },
    hints: [
      "${t.hint.replace(/"/g, '\\"')}"
    ],
    starter_sql: "SELECT\\n  -- Complete the relational query\\nFROM ${t.cols.length > 0 ? '' : ''}\\n;"
  }`;
});

const fileHeader = `// ============================================================================
// SAAS — LEVEL 2: RELATIONAL JOINS & SUBSCRIPTION AGGREGATIONS
// 100 Handcrafted, Non-Robotic Questions from Executive Decision-Makers
// Tables (9): accounts, pricing_plans, subscriptions, invoices, users, api_keys,
//             feature_usage, cloud_clusters, support_tickets
// ============================================================================

import { QuestionDefinition } from "./ecom-l1-questions";

export const SAAS_L2_QUESTIONS: QuestionDefinition[] = [
${outQuestions.join(',\n')}
];
`;

const targetPath = path.resolve('src/lib/content/saas-l2-questions.ts');
fs.writeFileSync(targetPath, fileHeader, 'utf-8');
console.log(`Successfully generated SAAS_L2_QUESTIONS: ${outQuestions.length} questions.`);
